apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+u3bgb5r9Mtf2+GfiNKeNA==,iv:yyUwK0m0yY3FRUxgEZPMfTgS/xrHlX+NtaxDdV9ZsKM=,tag:VdyfnOKVgkmmUBoaCAqzUQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:sHfC3KyPN7jd+SFn/C30BhMZwXtkTjbcP+zpLO2F1qJ6ijzKMw==,iv:evE10TfvrNi18svchg+WmuWpYpZsoPG+ijStMwiLK4E=,tag:LK0r/MpI82xSS86St+6Dvw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:zJbYYvDg7zRmr75nE8M=,iv:6ca7JXBCcWtzydAT63/DypAHhufxmRefxyr5Ia9NDXY=,tag:8dS8+HOL9LZyxB4WtqL4JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Mkt0SkJBQjFCL0l3OHJy
            MUx3YUQ3UWl0WWZMTkdsN3NCdkJWWE96cm5jCmpaeUhDQlhmaEFvdldrVmRNZW9Y
            ck9uSFhJWDN0eFVBd2ZZbnk2YUdqWHMKLS0tIFE0ZUdyTGZMblJ6SmtmZ1VJVm9E
            WmJPRUo3RExRSFRYUU1FUnl0VC95L0EK31HePeQS9gZtRd+vVwr9b4DbYkNOp5Cq
            ezvJdz6P0LFGRdoxcgdQMnHP+/9DMzoDafagemqKgGiibkATZppphw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T21:24:29Z"
    mac: ENC[AES256_GCM,data:zUMx0tsYZ2sz6QbrKIF4pF9J79htNiuYjG0EQy/S6jsq5R25WIj4VN1Z1bfKD2JvG8081d4qnwKj27YSmNib0GzfKjbyfdXYgGIXlnJ4nmbKKa75wFsDvnvAAEguuGtIj19HZSxYslkyEW7mpDUJwiT4HR+McHJ9MnfwmxxSW5Y=,iv:MjukvshlWIbP95lT9bez+Gtmoouzelun46ckvLwg8vw=,tag:Q2VGStybKMzlVNnbiZN/nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
