apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:F9lNlsr9SJML+dc7a9iCAw==,iv:Lav2iCA9O3JlEG8ac3LmfSw/j6nVdJyD+iXHLtVMQCM=,tag:vwHpvcmh3yQmbjd2KdMpdQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ZqL2TYYeE5TSBwXyBDR+CDcrlTYYBQEAFBH/o88ofwL6ssl7Qw==,iv:3Pt+wKXoPZ7F3om/pEIeP2SanUjnukwkaaPjHDCJnMM=,tag:QRjD1Oxwn3mNj5Lrg8BBZQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:j+Cf6Tnglh2onbBHFLo=,iv:tgTLFKtz2Gc8AxHTpbOnT0ta0Wvblo+tP618/D80ICs=,tag:ejHMIO0AJIt0oLeszbgtfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORmtEdDk3eGM2REd4RU5Z
            eGV5dzlmZE9CNm43aVJ4RW9YSmowTFBLbkRrCnAzWmxGTFY4aE54ZDlJUHhPczcz
            dnBkeUV2a2RHNFJqaDJDN3hhdEkrVkUKLS0tIFI2TGloRnpoYmZ3N2NzS3JtM2lY
            T1NNSlY1ZGorYnczU0tpSVlvSGlTNUkKhVqXzY0InliThbN8Jxiit8yW3YysRYCP
            1rfSb0xgkJs1nSvse7bfLTpe4FxUcL0Ce/eSbZhcKVf6JJDRCH/RGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T13:55:03Z"
    mac: ENC[AES256_GCM,data:MU5h1DnikskoP0dIobgLqczuOFxa8fbgu6WL2SJSVQJFUzd0PvvvuP4Ot9qoNE1sH55uuNwEpimyuMQa2XIAXUUlq4DkI4UOUe1uns5fCiReKP0fWwlNz2ipCdx/crkx3Nv1Vr/80JyF3EKs1PgcZKv0sWlrYoIV5UHC19DxyAg=,iv:yJg6tvl0cpeg3uMJ3/0KdJkOvmz4g1gAUnzqrbUGgGM=,tag:q7uGysL53vYLGR0T8l8aiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
