apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mCopXyzCmJ56DWhteSFi7g==,iv:D0/AE9PkwkF5EcNLTS2bQZBzTGHW166pYbWh4d1nEnE=,tag:jFXp9adfd/uCzo+OzCF8VQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:2GM8khokw5stIpBusiQjhkm6BAiL+SI/yai1Wjve2ztNBo3kWw==,iv:YN5D09sD00Dh9TuoEerz8esdtN65s4rdAMmnArokgtM=,tag:Wq+hIPJOqNs/IJm1qY3MOQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:W7R1h6YfSAWhMCeFWaE=,iv:sMbNkpMpINIRExRiqyKkQxAx7ar4nK+yRSwTzdxS51k=,tag:FENoMAv1aD9JIXT+486muw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NWdvV1J0QXlpNGZhV3JW
            d3ZYNVAySFJHTGhhY1dKM1B1UzlMVzBUTVdBCmlhRi8xRTEvSUlhWm1OVTNIMzlZ
            ZHU0QlkxZmkyT2JuYmtmV1JMelNXZWMKLS0tIDFqeXhsUnZ1RDVnZzhYYmRGdVUr
            TDhiZFJwMWxpT29oME5QSG5XSnZzaXcKwfwHNHutT2HrWpB+UiPRqd9H0wcB8XfM
            0ATtR1egocY34yhp73abezic/Y54eViCXbOXbJ7JT9cfTix0JahhTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T00:15:05Z"
    mac: ENC[AES256_GCM,data:mwDCcRqe7P1m7kaa+U7Te1MRNFdgsZVb9RvZ/Sz/ylSFzbeOX6Y16S2OUXRmaZ2kcZPwtjptbBgdADhtQo+98r+FxqfxS6we+9UDEoBBcMyYymHPzeW5Epfek1RQnZ81QGon9Q9yW17eBhbp5qBD3eBf/A2SHVULZnkaAwE075k=,iv:Pr6e7zI6NB9vIVa1oGUuGKKqzOo9zFoPoAgkuqAz7E0=,tag:qxCRKZm62D9wLEgwoXk5mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
