---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # - ./jellyfin/ks.yaml
  # - ./jellyseerr/ks.yaml
  # - ./plex/ks.yaml
  # - ./tautulli/ks.yaml
  # - ./wizarr/ks.yaml
