---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./calibre/ks.yaml
  # - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./jellyseerr/ks.yaml
  # - ./wizarr/ks.yaml
