---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      authentik-redis:
        annotations:
          secret.reloader.stakater.com/reload: authentik-redis-secret
        pod:
          automountServiceAccountToken: false
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.0
            command:
              - sh
            args:
              - -c
              - >-
                redis-server --requirepass $REDIS_PASSWORD
            env:
              REDIS_PORT: &port 6379
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: authentik-redis-secret
                    key: AUTHENTIK_REDIS_PASSWORD
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
            enabled: false
          redis:
            enabled: true
            port: *port
