---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-0
spec:
  restartPolicy: Never
  nodeName: kubernetes-0
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /
  containers:
  - name: alpine-0
    image: alpine
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-1
spec:
  restartPolicy: Never
  nodeName: kubernetes-1
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /
  containers:
  - name: alpine-1
    image: alpine
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-2
spec:
  restartPolicy: Never
  nodeName: kubernetes-2
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /
  containers:
  - name: alpine-2
    image: alpine
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]