---
apiVersion: v1
kind: Pod
metadata:
  name: disk-zap-0
spec:
  restartPolicy: Never
  nodeName: kubernetes-0
  containers:
  - name: disk-zap-0
    image: alpine
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args: ["-c", "apk add sgdisk;sgdisk --zap-all /dev/sdb;dd if=/dev/zero of=/dev/sdb bs=1M count=1000 oflag=direct;blkdiscard /dev/sdb;partprobe /dev/sdb"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-zap-1
spec:
  restartPolicy: Never
  nodeName: kubernetes-1
  containers:
  - name: disk-zap-1
    image: alpine
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args: ["-c", "apk add sgdisk;sgdisk --zap-all /dev/sdb;dd if=/dev/zero of=/dev/sdb bs=1M count=1000 oflag=direct;blkdiscard /dev/sdb;partprobe /dev/sdb"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-zap-2
spec:
  restartPolicy: Never
  nodeName: kubernetes-2
  containers:
  - name: disk-zap-2
    image: alpine
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args: ["-c", "apk add sgdisk;sgdisk --zap-all /dev/sdb;dd if=/dev/zero of=/dev/sdb bs=1M count=1000 oflag=direct;blkdiscard /dev/sdb;partprobe /dev/sdb"]
