---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-0
spec:
  restartPolicy: Never
  nodeName: kubernetes-0
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /var/lib/rook
  containers:
  - name: disk-clean
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node/rook-data
    command: ["/bin/sh", "-c", "rm -rf /node/rook-data/*"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-1
spec:
  restartPolicy: Never
  nodeName: kubernetes-1
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /var/lib/rook
  containers:
  - name: disk-clean
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node/rook-data
    command: ["/bin/sh", "-c", "rm -rf /node/rook-data/*"]
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-2
spec:
  restartPolicy: Never
  nodeName: kubernetes-2
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /var/lib/rook
  containers:
  - name: disk-clean
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node/rook-data
    command: ["/bin/sh", "-c", "rm -rf /node/rook-data/*"]
