---
apiVersion: v1
kind: Pod
metadata:
  name: jellyfin-fix
spec:
  restartPolicy: Never
  nodeName: kubernetes-0
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /var/lib/rook
  containers:
  - name: disk-clean-0
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node/rook-data
    command: ["/bin/sh"]
    args: ["-c", "echo BEFORE:;ls -alh /node/rook-data/;rm -rf /node/rook-data/*;echo AFTER:;ls -alh /node/rook-data/"]
