---
apiVersion: v1
kind: Pod
metadata:
  name: jellyfin-fix
spec:
  restartPolicy: Never
  nodeName: kubernetes-2
  volumes:
  - name: var
    hostPath:
      path: /var
  containers:
  - name: disk-clean-0
    image: busybox
    securityContext:
      privileged: true
    volumeMounts:
    - name: var
      mountPath: /node/var
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
