apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: nfs-test
    image: ubuntu
    command: [ "sh", "-c", "sleep 1h" ]

