apiVersion: v1
kind: Pod
metadata:
  name: jellyfin-debug
  namespace: media
spec:
  volumes:
    - name: jellyfin
      persistentVolumeClaim:
        claimName: config-jellyfin-0
  containers:
    - name: jellyfin-debug
      image: jansanchez/sqlite-alpine
      volumeMounts:
        - mountPath: "/config"
          name: jellyfin
      command: ["/bin/sh"]
      args: ["-c","sleep 1h"]
