---
apiVersion: v1
kind: Pod
metadata:
  name: disk-debug
spec:
  restartPolicy: Never
  nodeName: kubernetes-0
  volumes:
  - name: rook-data-dir
    hostPath:
      path: /
  containers:
  - name: disk-debug
    image: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - name: rook-data-dir
      mountPath: /node/rook-data
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    # args: ["-c", "echo BEFORE:;ls -alh /node/rook-data/;rm -rf /node/rook-data/*;echo AFTER:;ls -alh /node/rook-data/"]
  dnsConfig:
    nameservers:
      - 1.1.1.1