---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder
  namespace: development
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-secret
    creationPolicy: Owner
    template:
      data:
        # App
        CODER__POSTGRES_HOST: &dbHost postgres-rw.db.svc.cluster.local
        CODER__POSTGRES_PORT: "5432"
        CODER__POSTGRES_USER: &dbUser "{{ .CODER_POSTGRES_USER }}"
        CODER__POSTGRES_PASSWORD: &dbPass "{{ .CODER_POSTGRES_PASSWORD }}"
        CODER__POSTGRES_MAIN_DB: coder
        CODER_PG_CONNECTION_URL: "postgres://{{ .CODER_POSTGRES_USER }}:{{ .CODER_POSTGRES_PASSWORD }}@postgres-rw.db.svc.cluster.local/coder"
        # OIDC
        CODER_OIDC_ISSUER_URL: "{{ .CODER_OIDC_ISSUER_URL }}"
        CODER_OIDC_EMAIL_DOMAIN: "{{ .CODER_OIDC_EMAIL_DOMAIN }}"
        CODER_OIDC_CLIENT_ID: "{{ .CODER_OIDC_CLIENT_ID }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .CODER_OIDC_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: coder
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: coder
