---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.14.2
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: coder-secret
    coder:
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.3
          imagePullPolicy: IfNotPresent
          envFrom: &envFrom
            - secretRef:
                name: coder-secret
      envFrom: *envFrom
      # env:
        # - name: CODER_ACCESS_URL
        #   value: http://coder.phekno.io
        # - name: CODER_WILDCARD_ACCESS_URL
        #   value: "*.coder.phekno.io"
      ingress:
        enable: true
        className: internal
        host: "coder.${SECRET_DOMAIN}"
        wildcardHost: "*.coder.${SECRET_DOMAIN}"
        tls:
          enabled: false
