kind: ENC[AES256_GCM,data:7Z5W9E+t,iv:jR7oEtxp5USn4MYD25hOns7bbI9ee3Q17NWcJeiR6ts=,tag:kRvodPywbnh9BueDB/vXRA==,type:str]
ansible_user: ENC[AES256_GCM,data:JtZwtSf+,iv:U+doYAMJbwwV9+Q0Q+1tcnDVzlAg6gRnw6vRLclQccU=,tag:bxhz53sH1MZuMSMkHUoDBA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KxFdd8PRdsm59w==,iv:pK07pKSLYIZjEXMTexm1MjwtWjbAMR+ap54mcSodGVg=,tag:AlTcZK+v4nSf4u5+Anunqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTmpiWWRqZXVTd0p2OTRm
            R1crK0hJWUtxRXJuL1NJMDJscnUvSkMvWlRjCjBmUG9aMnJjWDB5eTFyRXI5em9C
            OVJjT0JmdXdHSzZoR3JDZnpTeC9rUDAKLS0tIC92b3ZGTnBjOTVGa0pCWTFEV052
            NlRNTW4yUXBWVzhsWnhOdTlnMGJBUGcKCxa35aD+TD6s3IB7L5KO/iS+zM9r0ifq
            nfsk4Rro7ig3cKITfhD1XcvbQmexznV7V+7S8M2V7j50Hwr1PVX/cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T03:03:43Z"
    mac: ENC[AES256_GCM,data:yvGuFoXKC07MF3rVYRDtJd187d3fqQ7Ilj2wuhZr2hbnke/AcaOzEMBun9kLNrUHCdZdbA1qYMxqb798oLKeGUHudekvxGYwTH1RG9Qe87UvftgMpyYw8N3DF4TQMj+VQCJNnqQj9bOo8+PYBB3NyKxvyHhBDLWX7VkCNHbZKME=,iv:nuBLhMqJzgXwjIRedCdgYtB+gVlBDrecfeiwTVJXMJ4=,tag:js1X+aVp7fNg/WT9W5fOHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
