kind: ENC[AES256_GCM,data:z5Op0/lA,iv:TYRlP/WP01sbcyX/VN+ssmOYyr7RI3QwKaIobzDNdNU=,tag:GWk7W2N+sF3nT8S4g0n11Q==,type:str]
ansible_user: ENC[AES256_GCM,data:wOD3ZdXt,iv:h3x6VTD9FzjVBdy3KmbeIUuMgykQ8HIHuoK/nDDUjPY=,tag:0ajH1tYi0Y+dpBvhx2WFMQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:SyI5FgYfFNUiBg==,iv:zmO6XdOlW4mU0r3tPT4YzvAe+wLZlItYjvfDNS8jdnI=,tag:ZEB/ZCYmQzMuBmlp5qKEqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWm5qckNBZzZRZWtrVENj
            QUVTZHQ3c3FTdHpGcS82YUZmK3dBZzk0RndvCm9rWkF5d0o2L0sxSFNnczJTRG9w
            NDd3MHpvRzdNTFhZd2ViT2lCazlBQjAKLS0tIHFMRyt1ZUlPRTVQZzhDSlpSQW5a
            bE1nbU9EaHRCMnc1Y2huZWR0ZSs4OHcKZpGBmb1UQe7qUwup6HYG5F+PB+CZ7kF2
            EeNlMfAbXyWiEulP0iRN2E+bwqbRC47cx+NEMEZT5jNxZ7ziYDQ7YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:49:01Z"
    mac: ENC[AES256_GCM,data:irKDRDlFWlj64plQqvExpWCF1I4UTejfioW+A6/IaRZCGImi6SSRpISC+FtiXl9b0PSOW7AlGUtMHAIHwTIxKocBJ/eRN7GmbQCxO8pz7n9WBPAte30rB9pGBNM1DZrc2xkkm9waMeahi/3701+4qb4Y0m97YZ6bGw80H31EZo4=,iv:m1dCPRD5uendd1g66XyfdyCnu55aVHEbeHG4xKgBpOQ=,tag:uSnBLXBxk0mVbd+NdLbY/g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
