kind: ENC[AES256_GCM,data:kroGU3qa,iv:58mXg84OqEvtE0E0X5HezmkRlAwr1zWZ3XNm+sM9HvE=,tag:fi70SIkcQZN1ucbo7gvE3w==,type:str]
ansible_user: ENC[AES256_GCM,data:z5mtN9Xa,iv:XT8XG1pSpC2yBtoOHuT7CJuTTrBENvVviDvrdY0oBXo=,tag:V9PNKc9uEoufGw4mgrjK9A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tibgo0NfR+r8dw==,iv:peP5YoONA3Lqpivv8Q1m+m+xdJeX3Mep9lf0tnufa5s=,tag:TEBMbKR7Xb6Ljdfj+eVECw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXA5T0Z1YTNHcDZlUzRB
            Y2FUYlRvcEtWQmpMNTlMSWRma1NJK3N1cTBnCjBpMUlKYzFOLzQwTDBmRXV5OUtK
            Ym0wZkxlNHhYbE9ZdU44dk5jamFUVUUKLS0tIFRDWS85Qk9oYjlmOUF2cElaQkVV
            eWZUUlNoTmtDU0xHQWdjbldmTDRKU2sKTVQSv4hu8cH//8/+2PgPinuB1OgxDpZU
            IpcLeJBQ9ZPM6mximsziBqEVsa+VekvZmRCH/bwBBixuoGW/LzmzUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T18:35:27Z"
    mac: ENC[AES256_GCM,data:7gH7scraKR7+A0h7H6Zh8cYTtW4cIZnW7X7vwSpBSpyCN2WFUadb0nNjJwIgK8hQEPOpYNk9KZaeNUqhFkSc+M+ey/wFe/DrwgJeHgjOebNwRwQURUeqS8LDbtLm8Mq/1GULctk1sahIxC4meLVcJAxJSphhWsLJdL8sgxiuzII=,iv:2iExuTHzYxMe6Ly7VJmP7ZxaCT0MiJNqnLSIdJ7bWAA=,tag:CEq4fZQ80DGCoaMmYQj8IA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
