---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      immich-redis:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.0@sha256:79676a8f74e4aed85b6d6a2f4e4e3e55d8a229baa7168362e592bbfdc67b0c9b
            env:
              REDIS_REPLICATION_MODE: master
            resources:
              requests:
                cpu: 5m
                memory: 256M
              limits:
                memory: 256M
    service:
      app:
        controller: *app
        ports:
          http:
            enabled: false
            port: 80
          redis:
            enabled: true
            port: 6379
