---
apiVersion: v1
kind: Service
metadata:
  name: postgres-vectors-lb
  namespace: db
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pg-vectors.${SECRET_DOMAIN}
    lbipam.cilium.io/ips: ${SVC_VECTORS_ADDR}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres-vectors
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-vectors
    role: primary
