apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:8zHhgIrHWZxo1QSZU3mrECwR/+kFBj9mPcxODEX1h4Ux2zw7,iv:uuMLYHUYjUlWcMntshdRk0oYstzdRUSDQL8IiOftGdY=,tag:QZoB2H5onVEF2XhZEOVcXw==,type:str]
    credentials.json: ENC[AES256_GCM,data:zpFnZiNen+C5VTgunFGl4NOiQiNpfq9WM8GZhTTwqqempI9OpxKkJy+bdOQwatt79KRLSqH5Te/3LgajixWdZlSP7VayLAwM7yiCzY6v2PrQIU6M+nLh1FDyEvQArQU6vNJM3SrZAF7QCKnKd5xrtSxJx7kVTeucqq1+wckZCxNXkT7qBdxqvyRKb6AT90SmiV0Qc1thF43wbaE+VhaEe5yYmX8xvU+I34O1d8msZQ==,iv:GOm3Kk90gDn1odeLw0P1CIMKsu5Qhe+9NbsXdurbjGY=,tag:ZazvRriqeZ/yY1iVx42Shg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcUwzTGlEZEkxazRBbkdV
            WEpYVlQ4d3NMMXR1VFRWcU56WjJJWFJJMGk4CkRRcG4zQzJFcGcvYVExTnZabG4v
            bmlZcmlNcUtiaTZIemJzZFZqVnlDWTgKLS0tIGZUcEx3VTFEaVo3YzlZSHc0dk9X
            Nm9PNnFRTFVJU2phRysvMEZmcXg3c2cK8K7265hERiYq2aPuE08B+O5dldBnD+Eg
            X+rx0S7jBiddvrCsc5IWHKLDEoiuaVKyo0t0a6iF92/ysqrIVLb+Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T01:43:12Z"
    mac: ENC[AES256_GCM,data:/5jMEHG3wiQO0bSkA+LV68ZWZ9wcHmbrBSAlpGynlXm5P1/YfiYV5SNtjNjCyTxAevFBXqjkyvAXeXVyOKWR1ck/LLaXBxj6/76aqR9JYzc6YzDaY6b3SCI4vOe68waPNsjEiCk64xjIpV6WvnPrCBfaS9DT1uN0L8psNLQ2IUM=,iv:Q9sGMFSCIDp1TSM5FLhRJdVuD4ww/tvTuK4u+pwq+Ek=,tag:6fqbHspzY3/NgDbLW+v8LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
