apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GutmwJoQMEOSfunqM+WmHLtteo9UcTS1Cemlauls5JAvvOGX,iv:rS5dFvREbJuDqA+WkzCEgNbUnsBoq3TUXtMoHrNHqo0=,tag:POTtaJAgSG4QO0TXutovjw==,type:str]
    credentials.json: ENC[AES256_GCM,data:g96AomYt9O4wEiRusnSm11TrMbISUPjHjA6WdtSXzUOoPBBdPeyq815feuXqbDNPqimuE/RZQXDnxXckhN6132n9sk8xJJb51DrB+fiOyLjzB45eQIav5izJowQHAmwmcVO8yejYo+VwaqgA/4c10kS2TSsNeS9AMoKQbnKxEVQSH8uxIt2Yp72OsxxVDb925GKvRSPUzHSmGmJQDSBsIe4ryswxrA7gooFcLq7XHw==,iv:osN2zlaIN8UIMVHc8jsGDjdzt7ta4nMUCUHUIgZqtdk=,tag:RpwqSGRlxfsOlc6WAILdtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SndDRFpxZS9TaU9mVDRr
            TUE1eU5QRHV3ZWZ1QzM0ZWZSdWRHaWJGMkVrCmJUSTlBVkZ4ZlB0YlR5NGIyMnd1
            V2V4YTdvVGRYL0tMUzU5THJSbUc3Z3MKLS0tIEpMN0g2N3FwakJXQVJxdWF4bCs5
            U29hQ2dJNDFxYmxhdjNmOTFMalhrb3MKhHXU0SguNnl7ZiSnKv/QJN3R7dM0ayKZ
            OrMkfz2uBAruR+tT27fAJDgisalc+Nx8dMcmFWjSY3JgmmWCSvbVuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T02:07:47Z"
    mac: ENC[AES256_GCM,data:Cw05hzVgMxxrXJCv/cpMGICPhfq/y0D5wbcCTPvxggxYs/3/KQjTV12hgkie3G7D7GX99yDPdnMdjPjSzXoObRqvB6EpzpugeDtKulOLgHhMEE2vgr24F7sJhk1naVVGzoDCguSnvJ5sd+yF2yN2OOcOvO87X3YgHK5FeG4Fqqg=,iv:lbxsNilRjyb2j6uBc+4k+tITLmwzFmgf4gbrpQnnfvY=,tag:vIdmXMCVUoaQ6radn9fcHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
