apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vGQma0NVdcMqXs5+OExb9zh8JBaB01q5yw3OZ5HHdc3o0AkB,iv:rql36Y62cY9xJW5/RFNIgdx6u5pSUzh8I2aai/4VaqQ=,tag:v/PPbNeOa/zwwQSq5P7SQg==,type:str]
    credentials.json: ENC[AES256_GCM,data:9qYtQVA5aufM+bFIBz2lireCcMFK9dcI5N+L3CnNMGm9RHU0/mc4e1f9WCx2WGdzJkvp+T/IVJKeB3zypbVIPV8d8JZqX9rzBwPjAm/NPvsKd2VCljIfJDbZioc44eYSnP7fVZnzTq0Y+CXQRczb3TS4yjfkpMRZ7MdFaoDnYDti7T9U/OgVz9DWkOMHPQRASJ3uWXpWQnsVSZUfNh0cYQWAXZmX48/FeYAuV7TWnA==,iv:wWFQRl2oztl4CXiHEaUXPrNmx+2nOFdPXUHltWptDZw=,tag:kOiIN/Iu1A1b/y3evFk6zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cndGS1l2UVBaZHdpZFBW
            TU1SZlNtM0dqVHdyN0FST2ZpYWUxTldmK2pZCi9BRWIzUXd3QmVtaWpvT2hubzla
            ZWk5N2xJelVBTUFQMXJsMzZTbHo2K28KLS0tIGpFdGUwL24vbGliRFJ2VkNRMTlG
            V1NZOFVvWFVya21sN1AxelF0aFVoekkKau0MaZmiTx94MOEXGD6n9H/rO5aHHP51
            MrC/FhMoQaT5Ky9ZdNd5jDpG9Wn+uw0RPt/OZrOelZXY5i0W8drKgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:50:47Z"
    mac: ENC[AES256_GCM,data:4PXedsmNMSHsDS4Q0wDcm5+SkpN7vXyodJ1MCmHp1SgmfO6za8ZRGmdZUz+wwMRG+DmyFoOqV47ixdXNXfzn8kKM1y9TAxnUjIjgk6A5NAUvmfWVn5AviAZy8FpomC9em60n7LgoHbHWqDBAaFqFQcgfCIzwHq+LRDlh4iU0+po=,iv:lC7wV/9IoeLJ2X98k2TN07kPTvLDsOQpBWm3d7MzwUs=,tag:HBeqd1ZP2lL3/EQPe16Y+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
