apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:bDI9YZ8=,iv:76Q5kf8L8L+ZIiXSRJBgS7T0zRtY1y9Xqcx/bSwD+UA=,tag:kEmqnpryPNCVfHkOwIxnCg==,type:str]
    admin-password: ENC[AES256_GCM,data:574DPMCllw4pDUlfPnXYiw==,iv:T0/hsPEUQe3dCd+wxtmVMin6HxLHLjRaDC+HkM30ipE=,tag:en4IheK6QtS8us/Ux8oUVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWlFPVld6Ukd3UU1hcE5U
            blNyN3ZhTEVmSHJlaVVQT2lkMGhCajBqMHpRClB3blVtNEFreUQvbk93c2g5OThZ
            Smh5blVkU0V2ZWx0aXMwdW5DNU1HV1UKLS0tIFlrZUtpV0o4Yk5GTUFnY283SzRE
            ZGZqM05lWXFaNDRadERUcHc2OWhrL3MKvKiTJGB8a6hWZGvB7OLmWPH1YAvpEHoU
            8xfB/o7TLLZWtLbkREdccxOam63cP7a0ARV+kCdWjt1h9tV2UmAKSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:49:02Z"
    mac: ENC[AES256_GCM,data:u/2r7TJ4xs0Nxt7vWbZ5fNXIAi93zhQVUZfIXOKaStsShaR090ut2LAVHcGaLfx5rZ3LNww0+R15KBsiNaJwp0LGz1qu433sArx3x6x8FYf2lcpTJRH6RT1himHh2VyF5ThqpfVlpQMlRuFtUGRM8TPUfPZfTlGWCAmt4aRPNe4=,iv:Za3Tvh1RfqxRw4gah8Z2Ybtz6jUzvZoszke4nJDJ0As=,tag:vJLCm1+U+jE+53tB68hk7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
