apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:Ncal3Ww=,iv:pScGO0HpkG9iQpA/fwqk69JPu3YM+Vum4e455wGkDw0=,tag:xxFctYh8NOK9+MDFPw5ZLA==,type:str]
    admin-password: ENC[AES256_GCM,data:1CQGGHTTXFLbNw==,iv:dSvqPuzeogAfZtYg6BkMhrzmGCgziiR6mPGPxUlUF6E=,tag:VcpOKyoMt3FjkS6qYfkyvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSTcxVmtQZGdNMHRIbWdy
            eEd4d1puWUNhbmtSaVVwakNPaUNuUUdCZWtnCkZWRkRGbzVBL3ZqdkMra2JLbG1u
            cEhPMjZjVDZweXIwRHdUUk80dEtGYzAKLS0tIEZvV1BRbnhjMmlNTnVFRnJPLzYy
            aGIxcGlhT3ovNnhmUGRlVVlUNElRSjgK0c6CKM8VfobwCF+LZy+Ts4WK4Ifkj8B6
            fs7F5oVNk24yVdHQdkteP+EnOrK2p8JqWb6xckoxpgUG10ostRZ/NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T13:54:39Z"
    mac: ENC[AES256_GCM,data:sFT+1M3J79q862rOgkVYfwqZlxhY3uR72abCQr9fMcuR/JwDRKE5NQuYltUlu3/ky9CNmnlRTIEhY/Ch3aeO/wbC/OczwCgrfi86cRulvdjjsdl8LQzpgDT0+w6LXImyImiDqN8Rysg7jSQ/l7dz1x0tTjWz/BDx809xhioXRAk=,iv:P5bjZKqFP3y3IFIr76aSoiNKvgQU46E6AXyCoP0BNMc=,tag:Qys71RAVzPJV6wv4amGkLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
