apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:+WQIFpY=,iv:rhdxQInjQRTv13aGfvEIuw5hxtiOBWmXrwqBaReAp94=,tag:9BLnMw1pA4fFgQp/gym6tw==,type:str]
    admin-password: ENC[AES256_GCM,data:Eo6rEIOHvN2tS3bBMnaUdw==,iv:U4EQwd1QZPnpTdBr4v0PIAvGCbOKXCLMdbOcgoo1m6U=,tag:oClaiZOIPk5QMSxLmVjrHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VFRxYmVEc2pKakp1cGlh
            aFJEaFplT2UyNzBWb1JoSkFSVXp3N0ZFWldRClB1ZnZ1Z084eHhXc3kvdVFITTBm
            SXo0T3czK2k2UlZFZ0pzSnNpTTNhYzgKLS0tIFhMZUFCWU5DUmpTV1RVSzdFUE5z
            TVlhdW9jbmd0ekNSd0hhNm1RU045elEKt3ULtsvx7LqrA7oG4CdfC0+g5y4vpBF9
            2sGYzBCDSdc+qY2FICx+f8pqLXPhhtYiQ6JAkQx9vqy7H7CUW1w06A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T18:35:27Z"
    mac: ENC[AES256_GCM,data:8ILAn/2EiiYJT4q+G0h68RsrCOvRurakOhEa0/2Y1oT97WATi9QCDqIvL0js/TwOY3UmUHWzRrzYyOkUr50py71noX81DjJrDobbqOjUtgDttjA2ZBofId+CG22h8lanFDs76X913jQH7I6oAxHIZwub51jbMGQKR5p4bY0+pPg=,iv:B04nFmPJkPlscxPxy4lT6W2V4yXGaIWRi8yQ0KI2pdU=,tag:BCBY9NinAFWiFl5FnG6eiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
