apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:F4Hrrukfr8H4PcLjLEpFdXfg2Q5Lky+1gn55iV6CCDBiZehKR6ZwLg==,iv:uRmhQEtflRe1WmGUIHBbVGIgvz6i3IwxHPALCdw/RNM=,tag:StY2LoNtz/4YOKaYE+FChA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMlgyNHVSN0dHTGx0NERY
            RHA0N0w3YWVKTXArRDJGRytISEV3VzRmZEFvCnlMTXpLSmpxd0NIeXVkbUFGbldr
            Z0h4VWYxMGQxd2d6YUpjaUs2M3ZTK1kKLS0tIG5tSms4azNZd3Y4REVwdEIrcHlm
            b1pwMEdQU3FJbjJkdVN5Mm0wWG5YU2sKVc8rs1+RIM9pE99H36IXGa1jijqGFw+c
            Si4jowz0vVEElrBnRvTkRLAw5+oa/6GLq8fLHmoNev+LwwqKbsb8Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T02:24:54Z"
    mac: ENC[AES256_GCM,data:IB6VwI7SsGmLPXIUbXK28YjHeh2FKdLZv9cP+ptJuJZ+FrDiPv6jyUiW74zXpFc41aAbpnNp2nFvOQivLg6yPwAf/uh8Fb2K2IK/GpRQeIOztzRscEW4uJPIIkJLVxpj5HB6VtAJ90Xyplxu4MiSN84zRifTY87sidB/p5mkp68=,iv:4OdSpFX7OPvL1aU2eWwwY7bC0XeItwao53FZvZ38ckQ=,tag:32fXECMmt8aWNHUuqMac1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
