apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:N1vyKECGhW/YsprWJdi7sfPqUqCF+5rjt7xRH/4V/qAVa1Jm/MQUBQ==,iv:x59TxUJ5IXyhlVievmtuw6GdjSmNw3ZrC7oQWwGi66s=,tag:hBgTtfHCGkkMPrGJuvpJqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZWpXWjZkeUJldktXWVQ4
            Q2dxSU8yWTNnbU9YdWNFY0g2M1hCK0VHekI4Cks0cVowZVhmelVaamZzU1FVYzN5
            dTBLa3dXNlcxRUdmQzAvL3kxWStFYjgKLS0tIEdoMGovdjNndVVhS2hqeTkwN29M
            dGJsQ2wvNlVkV1lZTSsyeHR0RmdaTU0KoPwb7wrCgeSuNqaBFuLuiTIylFUVzFib
            xRCS4yDLejxTs87yi4JfOJyFSqn1622qbsDRt+Wic1YSIqyYXhtodg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T17:04:53Z"
    mac: ENC[AES256_GCM,data:qPGsUsvyEWLf0UnhQHmydQBcTmGPO3prJ8g7SH6DT3k8gtKUjFL0IuORv190FGpeDhJrc3vxRTKESQZIShsU+YMCxVbggH/62TOZYjghLupQ8By+BeOhW35Ivm9siLs51IjCUGD/ZTW7aeZ7EnIodoceiGaL9dtPNh2ec35EKrE=,iv:vYj4CGH3uxInuuwFc6YqpVVgC1MldOYVtZbC4ugVP/U=,tag:ur8kqpGo6UIyAGEzFIKI6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
