apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:9+bbXwpDVbGkPommdWAS/GxlO24rCX2Uyb6XUC7syD8Dnr2B+i0HtQ==,iv:jSPH2U/WK3R2Qvk+q6lN0euaSnKrFzWZLYWJWuLVNco=,tag:PhB3RShu96fLOhbj9m5OqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNGI4MWNHcWJMekhmVVFt
            RC8rNlpkQjdIMWRnWmtnME0rclM3cGk3RVQ0CnVibTVXL2pZUmZiR3BBU3RlS3hN
            YnIxYytCUE45RG9FOVA4UkhpOEFzNjAKLS0tIDZidjdkWUNrN2lCNzJWZDc0QmdC
            a2VHRUVPSG5lYXlrcmpqMy92d0dEN3MK/P5QyAhu088/O+WNQQCNWP96GGPLUAi6
            vtzgJaZ9e2AVzjJDMBswlmU5xxHwbArBJFsul8Az1/W1z9HRy04oVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T14:19:21Z"
    mac: ENC[AES256_GCM,data:+F+jAeszpjuW8WJavmNtnWK3RZ6iExRV67afjhsGyuvZCy3xR9picakJrl6PTuA/NMqwE+6f83PmcXeVyvKqfwfWIf5XakN4X3cGyOkgcuWHMAoBaGB/+E61vVL0Q5nYHs9y5n7LYJ4rSRCE+M9+sGxi36dZpsWTI5/x+9Fk9ck=,iv:6mJrSBBLmwsnTLctvoXuIrDvA2939kDZlgkS7zZgSF0=,tag:3DoEfN+Fd8KXaCzdn1q++g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
