---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-restic-restore-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jellyfin-restic-restore-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .BUCKET_NAME }}/jellyfin"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyfin-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: jellyfin-restic-restore-secret
    # Use an existing PVC, don't provision a new one
    cacheStorageClassName: ceph-block
    destinationPVC: config-jellyfin-0
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

