---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whisparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: whisparr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WHISPARR__API_KEY: "{{ .WHISPARR__API_KEY }}"
        WHISPARR__POSTGRES_HOST: &dbHost postgres-rw.db.svc.cluster.local
        WHISPARR__POSTGRES_LOG_DB: whisparr_log
        WHISPARR__POSTGRES_MAIN_DB: whisparr_main
        WHISPARR__POSTGRES_PASSWORD: &dbPass "{{ .WHISPARR__POSTGRES_PASSWORD }}"
        WHISPARR__POSTGRES_PORT: "5432"
        WHISPARR__POSTGRES_USER: &dbUser whisparr
        # --
        INIT_POSTGRES_DBNAME: whisparr-main whisparr-logs
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: whisparr
    - extract:
        key: cloudnative-pg
