---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    template:
      engineVersion: v2
      data:
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY }}"
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName authelia
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: &dbHost postgres-rw.db.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .AUTHELIA_POSTGRES_USERNAME }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .AUTHELIA_POSTGRES_PASSWORD }}"
        # AUTHELIA_DUO_API_HOSTNAME: "{{ .AUTHELIA_DUO_API_HOSTNAME }}"
        # AUTHELIA_DUO_API_INTEGRATION_KEY: "{{ .AUTHELIIA_DUO_API_INTEGRATION_KEY }}"
        # AUTHELIA_DUO_API_SECRET_KEY: "{{ .AUTHELIA_DUO_API_SECRET_KEY }}"
        DUO_HOSTNAME: "{{ .AUTHELIA_DUO_API_HOSTNAME }}"
        DUO_INTEGRATION_KEY: "{{ .AUTHELIA_DUO_API_INTEGRATION_KEY }}"
        DUO_SECRET_KEY: "{{ .AUTHELIA_DUO_API_SECRET_KEY }}"
        # AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        # AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        GRAFANA_OAUTH_CLIENT_SECRET_HASH: "{{ .GRAFANA_OAUTH_CLIENT_SECRET_HASH }}"
        IMMICH_OAUTH_CLIENT_SECRET_HASH: "{{ .IMMICH_OAUTH_CLIENT_SECRET_HASH }}"
        GITEA_OAUTH_CLIENT_SECRET_HASH: "{{ .GITEA_OAUTH_CLIENT_SECRET_HASH }}"
        CODER_OIDC_CLIENT_SECRET_HASH: "{{ .CODER_OIDC_CLIENT_SECRET_HASH }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: cloudnative-pg
    - extract:
        key: grafana
    - extract:
        key: immich
    - extract:
        key: gitea
    - extract:
        key: coder
    - extract:
        key: lldap
    - extract:
        key: smtp
