apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: security
stringData:
    onepassword-credentials.json: ENC[AES256_GCM,data:lB+/J2miX5RAGjftAWjAnSYkxo6rh4d8phvo340U8lXpu+Ymt0yBigjkPkwvRFq8r3Ukyn/t0BxaLM3Lhvxv/Nzth403CtzNyT0hn4EwBoVw6ZaoLV3GdCQg8TK3sElWlNF1oZPUxX5+ve/yN5JLOWzgOcvzTkui6HTmrh3PD7MXe2Tg+fGMVJSq085VTLSnrSOrw4zbph0iLyFtAPMLgAxdNDNAWLpBpd+dFteoc1CXFitRKIGhfOPG36GwxREobUvoBrDZlg6EfwSX3/pK0A1XA1dLB9K7VYSMTGgRuE3XiY8h5h6T1O08zd7OqQjP3lsrHK+1CJnQDCY4xYkp2ZsotMb9/fbo200ttSU/zUJ0dQMCDy/fUH2OPPOkN5vB1lAIRSXE1NQ5IJ2YDlOFkUYMhs+Z8r0K/x4Lot1uj47J6o8SqiR7REHwEfy4Ws3HEIk3UtLSQswUE6wdazuuks7eMIv46ef0AZxZXujKBZta8K/lEyoKuvxsI9c3uN+kobk9TaNa/dXjMzvrzMFBad1DiRDYgBT6/mK4U5Mh4QQQqpB+ivZxriyyoNX3AW6n+L/VDyCWxPjkS5uzINCGaJikYsK8yQCUtuvQi/+AQXPuFhsllX9AbYmT0Jgodvt3JT17WSQwSteeD7HKUPF+mWpRV8PzW0KksSvb7Xga5Y5NOEDgBrBKeY7XczznH/VoNLKfq3HbCex3TeYCOZ2x3apJa9mNBPCwzD1/stpELd+y1Ti+Kyxzjky4jW8SUsWHxWkQHQtvq72+zjbRnt8w6RbxKZxxJH2MT4Dy92WpfwXSyzQGERbnJGqCjpdB0KA0U1SV1Gw303OU3czxqqsVcBCRel7ijzUtoS1OYPSpfCq2DskMSdatXg9Z8CXhWtmlfWd3A5BMDyTSzOX5P0GNsX/5hlplJ3ZWmBijfuZYBfIMvP98Q1ZgJJ4cHbqjyu+4dwdntgYzWDf1tjV1Ub195+A4VMUjG1SDmQ4ci8hUd+Ms+rDTB0908l9twKG6fPj/Ru8JU1L0MnZFvEvYXQ/OXjvIywGpjpUcVokOnoS9HvRKm3NqbMHtjv0e2dTqh38swGN59hHZOx3L8KvkOylS0+tidUL550Rrt3eGqrE28d7keMaWZDMiDUA3/HmFvgZk7EVaouYSMdL4a9tWY/l+rCCiBlMkCoqg3K8ztazLUL9DnOh8FdWAzcOpteIwvySa7FCHDPDWNGQRR6FMxbGvlpXFoyDPlcvms1TUF6ndORcLFRjFQ512/+9bYsx48QJY7D3683ZO3BBW41Kl3sfdz1dNvnV4ttfsVJUR3o0roVZCnR5TXI6Ct+IPxswwHiTnm6f5piDWIeFPISNoGswsneCw4+SKkwekbqvVdpc20EFfTyyVwTc67rZrttm95rxAjeVdrpB8YuufXXQPSlwlJmGXib5aVHdyWiorxGpBmAg/DQm+Yd5BKvaMTO7KvdJfT74umBFKC+jhOb8R58XRFhYpQLqfSMWtWOz7Uy8W7iFke5ts/2/A245LAVNdEiHNU+HkKh3B7Qz4whAnN4xdeYhS9HniZbXNUhPszlUvS63Fb7/2HPwqJsBV2BHCbtLs1YbtVnMIdo54T4K6tcPQix70laAWp1v6FF6NO5LPxpV+uHK8GXORan+tQhIAqLECSXZ3arrokj4/yaZNWD/ro/A6ismI4BkRfkeXOIzbUAF+CjbXCShwnbrkCi6zi70lcUIlfMrmniQH+DviMf0/PDUwF8lOvzZDWQ+iH/M9H/6EYjEe2EHuwNPu88M0nm3zz+jIzW9C6EX06gU4fB3H2r4F6olb8GReWNbQJeLckLCAnbvRNaxRfoYmDfpnFaMD7ZjrDVxBpdZ+yF8L37Usg69Y4At1x4QqP+c1JwGTe8N6r6ctIhFPx6TNydcm3JSlgmmi9YxbuZAwaA==,iv:+mXntt9BH2rZTdro2Yfs0dq21mD8hk7jT1r+059Kacc=,tag:xqzWTbLf5nYVtYDtwq1I0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZlFtdTdWbzB0NDlrdFdp
            alZ4Y3lWeThzdE9pOU9LTCtoME1zbHVXc2tZCnFyeXpsUnhiRWxlY094TE9DaEM3
            MGc5bzl5L2NIN014QUxMSm5MaXRGOEEKLS0tIDJlUWVDVm51cXp2MWUwNnQ2TE93
            RHNwVm5sT3BoYzJmbjRpNDRiVFZrTUkKSm33d3drtky1TgZfXSzZ57HC1k8DS0KH
            IRgcXYkW6ot1FCwu2/IIdtNRrM/iFCKybeF6tRQnMdcrjnR3PBNz3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T19:03:49Z"
    mac: ENC[AES256_GCM,data:t6xP0bZgyUH9gZWe6v1KJA2ozZgVGFtb7suMEkA7rPZQsIinLO1lhKsQGsY0MnoXBPkzDbbsdVeoUp+ReAnka3c25gLe+anTjO+QcoQcTxclB0BELllWoQbr6vzVsNEsDAhl97u4QJHUHKggILCR4l2zuwTKmafa+BSfUbEfgRk=,iv:C/X7vzQXGE/4xdZ24+kGpl4T/2TXMA7wE7d0Orm6678=,tag:HhmJ4pdkY5BxjESNYF+DZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:qPef2MVYl63TmInaXrxofQTT2RJvsB2pSmQ6wKxxZmyfJ0gANyQ3MzoqgAQp5YvFrfxNvDUf1k+UTloblMR2nTdFjheWtxHXWF3stB63U4rnOkM4qRwcxIEbWBspmA518Y8EVd/G7WhOmbmTFDm1s4LA6BckjUV/M33wIGY14LXLspTXX9j7YrNWbeQhVMCSMxYpxfHmkQfswq2fiROEK9ft7vaVjWp3M5d9zfz4wnzQgcTHMuSsjrwtWUSblv16hZRa+1FbgsaOG1h56k27lbw4BT3W3K4owRyhX9QTLorlIOuDusIS51AbnAz3EyjajJ02JVR9TxA/gfv/kX3YzSVJabDCwjgiQ3HIXlIRC8ZOvKANxIUFi3496PVj+Vh9HQhkTjjNY4ShlwaTB1i1wI/BTzqmYex1tRUvtm+mdvxsjYftBpl7Tt1BDn7rskptfAgltObeJWXZJUOFLxAAS3tWCpjKcuxnOfsLNq29PjdV7CoutyBA6AZ0jBNkDTYsqb3lWM7KHgZ1juceR4DM/PeK0FgHPh3p68LHEOk6JLVXz2IAFviPDAIJILDzmjWkuaRAGV2Oq5E9GqNGgIcp1aUzZ44ihR2lVqO12s1Ax7Hk0mGpREnxuh1CZDCUYuF3AvOXdj/jIDAvK1I8Tinbafbbc2EWEOXcu79flXE79cuygPxWOJNSYWEVG2K4ovGIYyMdY3ftTSIJH3eHGruHxaXZYEA4WfFLONhR8DMyxBTSIi/UvnnjJ4kwnWCx5T+9E4c99fcqfWfbFFoMqaIuaAzg7Dy1VrQzITxzhg5TkzoYtlNEVeaYt0OM6qoN9mwdox47PzICvfFGX+5trjZc7jV6,iv:f7L5oGH31TAPmVTvSIffr/9rdFt0Z0OQlMVJ4UV8obY=,tag:Hu0w0rxwhDMMkRr5mdIksA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZlFtdTdWbzB0NDlrdFdp
            alZ4Y3lWeThzdE9pOU9LTCtoME1zbHVXc2tZCnFyeXpsUnhiRWxlY094TE9DaEM3
            MGc5bzl5L2NIN014QUxMSm5MaXRGOEEKLS0tIDJlUWVDVm51cXp2MWUwNnQ2TE93
            RHNwVm5sT3BoYzJmbjRpNDRiVFZrTUkKSm33d3drtky1TgZfXSzZ57HC1k8DS0KH
            IRgcXYkW6ot1FCwu2/IIdtNRrM/iFCKybeF6tRQnMdcrjnR3PBNz3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T19:03:49Z"
    mac: ENC[AES256_GCM,data:t6xP0bZgyUH9gZWe6v1KJA2ozZgVGFtb7suMEkA7rPZQsIinLO1lhKsQGsY0MnoXBPkzDbbsdVeoUp+ReAnka3c25gLe+anTjO+QcoQcTxclB0BELllWoQbr6vzVsNEsDAhl97u4QJHUHKggILCR4l2zuwTKmafa+BSfUbEfgRk=,iv:C/X7vzQXGE/4xdZ24+kGpl4T/2TXMA7wE7d0Orm6678=,tag:HhmJ4pdkY5BxjESNYF+DZA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
