apiVersion: ENC[AES256_GCM,data:Quw=,iv:+fJmrdEiboNQMPdmm9xdKkHbQ25UQHE3gTocCT6tmhM=,tag:qYBeOOGgeVNY8SYQAYZeDg==,type:str]
kind: ENC[AES256_GCM,data:U8Db43gC,iv:llC22GzUrdgy5FMeiXhXQdI3yk99oJbCLIeYP4WdIjI=,tag:FVSp6sNPTtxhxS9kk14WJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RW6U7PxRFNVmTde+ai5ytNig5mS8dzFUdE4=,iv:MpdtHhpIPY4BwTZFTj81EtzdGT3YJUprOxrvNWSYWAY=,tag:Wf+tQPuCekOiw/zhSgUMjw==,type:str]
    namespace: ENC[AES256_GCM,data:bVryoyRUXrU=,iv:m3pSAUfsPWZT1taSy4+QXYf6oRunHjQzgOViK667/qk=,tag:MKcJ/je65S0MPVn88oFcdg==,type:str]
stringData:
    onepassword-credentials.json:
        verifier:
            salt: ENC[AES256_GCM,data:3ftDTk/IpJhWbkUWQmB3BP33dG7KLQ==,iv:PRV/QRu8sJybGGTD9mbOestqSbOKPk7Yafc31GNy0TQ=,tag:RNI7Dh62PK+lHkL3Z7GInw==,type:str]
            localHash: ENC[AES256_GCM,data:wGkygHDEToFlTC+z11QvUOAxWf+yLxbDMrqQjs/fBFmgiGTywnb4gSgCIg==,iv:5Y2I32w7osUviTk9RNFKtrhxGtt5F7nYmvYOqpuS/XI=,tag:sufnz3zCUdpooIV6Y4wbTA==,type:str]
        encCredentials:
            kid: ENC[AES256_GCM,data:rreibKxWxauRpCdw9O1xn9g=,iv:USpCtSZcnLRxtweZsXdfzbV7NqyPYrPamei8ThAGu24=,tag:tnh20WTbISWUNj/opDJ/tA==,type:str]
            enc: ENC[AES256_GCM,data:Nry25niDjw==,iv:VmA+/geWKR3pBUQnA8RNoyh4Kv9OHGh4T8Mbmg2oX6U=,tag:kCWjRghu73KBjyrFDMTcww==,type:str]
            cty: ENC[AES256_GCM,data:o9OX2ZHvYRoVYBQ=,iv:k90h4sQJkQdYpQyb7j6TNdzxPJrDtmzekX3nICHOdVk=,tag:n2eNGmZoMVvzDtqP6yVZKg==,type:str]
            iv: ENC[AES256_GCM,data:9kFQYKkQc4ncD7Vfn8R+XA==,iv:JtPjwVd1hsb0R2CftPiWBD2BNFZglCfErS/id+JVL4s=,tag:/zV6jzFjWOOhN6SGDxYwgA==,type:str]
            data: ENC[AES256_GCM,data:55u1Irs10EUqMgfcnJFgtkHRC40qXZiMirxxHXvH85ANCTtuABXOhpL35kk43UnBjS0XrcaCFlCbiL3yEfk2noN54IPmINo+ptpBuhaOrhwuL5JsBi/MqlAhH+ltkI3/fW0pKUS8y5DeasdeA4V9j6Rp29ydVcNdAT8VYHY8c4sjsnC6hW/Srmm9yo56HzXhVI65TFp6bIt2FxSk0uDlhJ6PuU1tO8Y53+u23VNQgrGrgxndrP2tpnFA5IB3h+LrQoUTrhiLUe7bVdtV6C1LMmOpTfmG/vF3YtvM6yzvECL2zsBbFdcC2MYkzTV53en0lQ1zu4RPTGTFbbh0uFw2OZ8lzv2pDhpRD98dzn4SvMwgbbK+n6kzDmonyZCIpEdFDAejxqT94yfUdfVdUFMwTq0bL1IcnL3Di9MgDSlIqQN5m9TXDh8neZlOPbFCTPgn6hQ2HHSnw/1s+kZCyKtRpCpTC00WVNV1iw7noYToW/7vDicCaIVJV1WeBeA0DpnPm5eEyxJTLZmFgK7dZpGbb6GSitrO6ysFnc/RrZ4M91UQPf75za5Z1RpLEIJy4W94LyuWsa1PesJN2Dab2dieN9qqv2mqDwn7aMmfw2+yrsVmqM4gKA+P0L3kq6FLi/35cnSPfhOeGDe/HpYUST5ulpsYn6LhpXlQ5FapKvzf7L7vYlJOYhp8Dvu6DMDgOYj5jWFvmyn2XUR8AONMT9/KE60Gvz9kx4tlSJ5XCXvxOS/m18GQUtlDiuW9UgpD+kj3F+Q+V0uO+jnX4jsVuIVmWtJlAss6dFxY0QliyBj7dQZJNEoW60EreBGQQq16+t31THX5uBdCkDDdsk//fhH56mCs,iv:SLjsb+M4QOJtMFlu/Rkmb202nc89QbaoYvGGiogK/84=,tag:7UWs0bnsGEXT49VDkxYeuA==,type:str]
        version: ENC[AES256_GCM,data:EQ==,iv:EO+rARqrTkTSWaVlPmr408+qTH67e/UJjAcAg++6yaw=,tag:Lz1kA+O28u6TirD4b1H/Wg==,type:str]
        deviceUuid: ENC[AES256_GCM,data:wzEagoXSca+P/UiYrX8MQuVpi+PHKwTZSXQ=,iv:gBRkAJRBUMGMGbkC/BrAvMlwJPPmzv+bAoN0iYTNd2A=,tag:2QGQ8N29e77zX0nQ/9PbJw==,type:str]
        uniqueKey:
            alg: ENC[AES256_GCM,data:/Pr22WeYEw==,iv:NrRdtFARzGesKxz2TZju7KYHChaRms1uNPy2Vg2J/yg=,tag:ZUDbJMGG2+31e6n7ab2ZmA==,type:str]
            ext: ENC[AES256_GCM,data:BzFomQ==,iv:+nr0R9Lj1FQZDWxECAmOZiTQYuXB7lD4NplRbEO5tkc=,tag:wfSdpuPsac6rSy8mTBoMPA==,type:bool]
            k: ENC[AES256_GCM,data:C5LEA2z+stddE1t34H3MqRT2gHd2CHwQAled+5pNWip+xS2KVNZgIkve2g==,iv:zWhwVGn5JRTLLuBDGR9aqStm7m5vtuWRjCdPdtm2M9I=,tag:njSE6MX9Q/4gzwvZH/hkuQ==,type:str]
            key_ops:
                - ENC[AES256_GCM,data:AatzvX3QqQ==,iv:KUX+5Pu7b2Q0hSI3tBysALppf9rTZcMnJAIXO5LzR4I=,tag:FpIEvYoamUy2KHUfIAXF9Q==,type:str]
                - ENC[AES256_GCM,data:ycX8QrHbZA==,iv:8v9xgOF0lp4c3bhZNR08sjzSjpEFCzh0ipetG/Nhkl8=,tag:dFWrwfIcUvhh4plFTuKnfQ==,type:str]
            kty: ENC[AES256_GCM,data:M2cK,iv:SmHluClYuSUievW5LK1zhn67Yq1HFaQr0EJgV/QfFu4=,tag:8xcqueqD1N8Q9mBuF4qeUA==,type:str]
            kid: ENC[AES256_GCM,data:BU3nnzF4vXlyIcZltL43wfoJZEQ246KdyXE=,iv:H4d/KWehM7udvwZxN3L9ldmnHjdaEdfe8Tiw/I1xS9k=,tag:RhVL1m0zsFQI+yIwLtDsZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUm16bmVwOFJ6RndmLzky
            YzZ1SUoycTFtamRRWDR2eWdpRU9IVVBmUldnCmhoajZEUGxVMXprR1pNZ2RNb3Z4
            MjNzLzNNZ0lVT25JdlU4bDJ5VFB0MjQKLS0tICtqY0hMMUVBK01YN0dUbURxbFRK
            ODAyRjN1MlRjaittVmkwaUhOcDh3SFkKot5nwaNt6s+B6Bk61koVowZfczQ0gGNs
            Bt5I9MG8Q4OpgSbDMHi/PSwnu17a7J7wRCN7JT2oXq+PN8gOgqf64A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T18:47:28Z"
    mac: ENC[AES256_GCM,data:az+WJjimwTm0mvbhoqXQLnyRzEgJihJCFZ4mbibaLXlTORB2+fZ7wfGKt1yhVPqkIGFkPaJ2v/uYlqYOTdQMoRevqJ1+vv7BK82Lsw9UYateK8RYui58w0pB/0EfB3fCBgyEj2VAcmDNxM71GHr1ndAAjxA1BHTIEKbo50nJ4/g=,iv:j0rXdkz7bSMS9ogo1uE+vYEi7OYS/AEl9Can3AmDtck=,tag:W3Jlow/OzK8hI1/YeXoeeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
---
apiVersion: ENC[AES256_GCM,data:Fjs=,iv:k9K5je/bUC0KWfjBUGRr80FqI6yTBDPRRzFSEaB+QH0=,tag:KoqVCqCBpP9LK3OMBJ0CzQ==,type:str]
kind: ENC[AES256_GCM,data:rGt7DeJ+,iv:lGoP4OvptIuKasuu6WDOBvwH2OztwA7nyRz4lk9x0+Y=,tag:tuGp6wHSDwqN5wXsR7bt5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eyXBrON5DcTzU3frqwriib5gB4dZ3+jNXg==,iv:IR81ej8Scf4G/+vehX1cnlGd27yxgTRbC32nJM+3tD0=,tag:spG2wTYM38470YNV5L2gbA==,type:str]
    namespace: ENC[AES256_GCM,data:dd2MoP/IYTc=,iv:J3cGq9cou+MtqpWJECz/utcYb4AVMQhVl8dgwjaVGKI=,tag:iGv3Dn2m2nN3ucuBaTa4Fg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:brDLQq1qusvHZYY2qMw+9BBuiE7qfqSdR+jUW6HWf3u8GIqDyOE4Ycuiu4cyA/WZi2r2IwwWT5vSNi5US8q5gTqDBn3jWN7RW9wGFn7DKHk0yvDe89TidjE5SDGkVQ0Da/JGAroZewIm6C1jPwgQ4RKrColS79HInCslq6r2qP28gaAN1a9lrl2Llapmnmjp5mWGSw9d+vxuyK6YLIiCVpRTBF/hyy5Uaggj1fan2BO9s+tj/w5409+Bl1dU3A1evirr7z9rMd4Bs8Ew1GoqGrGWCiuwyNt8hO4ksM3ojcbN4chPxlIFRKlzXi5Wm6MnQJNte35rH3GnFhiKacDYHX0RXoClulXcRHFPyQ/H2+3RozVxEou5zati0Xpe2SqwXvTtG1nXNlKZ5KEZDMyvZCxC0AAXeOKWAMVWQ92LZqOXYT5RuDPrsS3PDqaSOh8WNfpHBTZlx5q09Y2GslXDa2wcVW3RgMb3iI4zbcDwAR1/wJ8DSjONwXqL4ULkHRcfTnezojCDizADs8CFbjZ+vZdZhl5FO+t+8nFFkcYB9eLJ0FudiCdvI2JQs0X3TiBa07iP6qP41JAw062C9C6GyWE+qtarevXPO36xAOZylJYarwJiDuPYtrAwZ7psDMJLxfGwArEbXRrRT/9MKqbshgGE1giz5RLifsZar+ZR4KFoWjefZijiaf91HE6bLeN4os3x/kP2Ms5sDoRX96wPQGH18nodUz78eRifBElVG7Xil25PYLy9psJu9VZ7WElQUD9+jTcG1axnJwomiu/l3s9oZgvLZIAGnPUvAzVSQ329eaB03P4i5KtyG4u/HSq0KktzRO+8I3tjqMA3ZenIh2kv,iv:5tj/oc8AgkP+NDw65Kb3OxU4NNZ1Pv9ibyTzUQLVm2E=,tag:L3zLgzIiw7e7As/Oo/0eig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUm16bmVwOFJ6RndmLzky
            YzZ1SUoycTFtamRRWDR2eWdpRU9IVVBmUldnCmhoajZEUGxVMXprR1pNZ2RNb3Z4
            MjNzLzNNZ0lVT25JdlU4bDJ5VFB0MjQKLS0tICtqY0hMMUVBK01YN0dUbURxbFRK
            ODAyRjN1MlRjaittVmkwaUhOcDh3SFkKot5nwaNt6s+B6Bk61koVowZfczQ0gGNs
            Bt5I9MG8Q4OpgSbDMHi/PSwnu17a7J7wRCN7JT2oXq+PN8gOgqf64A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T18:47:28Z"
    mac: ENC[AES256_GCM,data:az+WJjimwTm0mvbhoqXQLnyRzEgJihJCFZ4mbibaLXlTORB2+fZ7wfGKt1yhVPqkIGFkPaJ2v/uYlqYOTdQMoRevqJ1+vv7BK82Lsw9UYateK8RYui58w0pB/0EfB3fCBgyEj2VAcmDNxM71GHr1ndAAjxA1BHTIEKbo50nJ4/g=,iv:j0rXdkz7bSMS9ogo1uE+vYEi7OYS/AEl9Can3AmDtck=,tag:W3Jlow/OzK8hI1/YeXoeeQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
