apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
  namespace: kube-system
stringData:
  onepassword-credentials.json: ENC[AES256_GCM,data:dAvlKmRcaMm7ZkSIexEjPdS80AItoyC/qstwiXt7c/twmlmORqt15U2aTAUoPSvoKJLi2EVAYVpkpiR4XuwEfTPA1wsaxo+Hjguk3Q/iwdspfJHvL3cpZAON5zjRYV6SfhJQzO1054ujqUCSC5ce47aFnWpGxolGgroQmqaZv+E0M4XtND7txZmR+vtdF3UJnfdhUbTCvJwwH/oLvhJPIWjNfvcv81+9kHvFwmnP304GUU5CzGQGYK8Ko4aMTqmc6fYvG4x6p+cueXseb91cFYIKoMfZ9uZnIetkpQEmXExpJxO1DkcW3o397T22l/4h2w3iMrvkMLA6zmrpL9kpWAnFKHftjMtBHaDjw2++T8sJXCBgsPfUliqzvHV+dWQ3cxM97r4yc2nIYSTykNJAMuM2hdCYSdI5Xb/gesJKbOrgzFyTegteYLAd+n7akJHQJuPe49dDYTR5JHGhyr42hNn8s4LHqmaOPWyWsMA1TSp8hOfT5mOiG9uCzAkiEHmU+XZtSi+HhR69lTVeA0gBQa5VwFfHzKT5XmXFAr+mBwxlBlJBH2aWHcZNKcy8ZHa7K5SACoquj21m6ap8KXUSu0lkTpHBYzSjwO8b7q1gWhvdz/RI0g1reYJIjMutczBRZjltjgAA+cBpQquauE6eiGIsSf6xQ1f9m5tbeOEdMAJnvaEzhaWBBtqbq0ydaKY6ofmbV8Tj+IfSZmrpsJYt/AMY6PfjLtXFSyH5yPC8xcm4ZPcDVX2dHFUF4PMKgSw//F5m29O432V/LF8lipM99+8ft1cZrqBp4Ui7dyWAPedTudgr7j3DHWIXaqszEU5EYgZNfgezTuBO/1WWLcUuyXkv0ZLRwsgoE5JHzAj8hHTQZNkizascpWI/Ax//p4Je7qTOJbSUmoR2AazLXH+9fMpP4NkIRKhaRvwU5V9+5oTja/z+QhiKc/7G5v66HpJ/G+pVWfafgz1/HZ5j7mPSO1hXUkj5QhuMKJWN0RxPmc0UeL8RLDRC0CudpqGGe63TJ9FtvaczQv1AZRcLip8BAmqxdhOnII7KoFREpprjlgfJsnYIXUBbXTtXjf2wrzYR1NcmT4OiX87N4PGG/a1ZGUpaUbrwStFtqhpXWMej7ug0tkZokleJXPASRk1AlpKnTmlHQ+d+owCsFZCYOUGxe9InPhEJRg+5T9Ajp3PVXCZBR563ejZKUwAhuTcMOIVNVWbFqbgsPjdqmrJlbUnHyirPLmjCJIrX+utFuEtMkt5fjsUtHXDrUKC3o2mF1kJl88OUCOW5R7B4mU1Bob+zLy9sFFlc/iJkS6MfXkT016o3MD9nKafUEfNtUF0z+3o7awkwxnhn3Jw5BLYSYFxoppc9gUrRwawc0QuS3CjdP/RPDEevqGXfErpQzdUmO2TYvu7gj/t18MaCKllcf2xPcPn/M2Vd9FBQXWxDdozXTjvWxvITNx6iqagtNGP2JJzV+0VShqdn1KIGdyxzDGxEDb/UVRQj77a+gC/pUX+/Y/O0Ctyl7F83cfR5VmBGwdzM3yHLkZyAVPLg+tfCJCc8/PSbM1XsRCC8YhXkCekUzDErossG5C9AOHipmjkgPAtk9XmCCAlPgqWV2KA562pFWwMivjGIjE9t8AlmS+gtt6UY5iLDFSpoq6LI/AnKaCLYEGzGSfmcWEX5Kv10hpS9jb4akmAIPsogjmJthcq6AtZJKqvXXnMPLZeGB+mYplVO9yZNrnsySp57tTu9UvHCmWVNVBLjbP2f23H5UhhM4olBi8mD5agoqN2KskmYCc+m+jJkXjxQvF/V2B1INpd6aXlfdxD2xrd+k5GqgOmOibuJfyzrBHkUvt/XgToiKKs7jpluNg0r3jT50GUQtt1C+Jiswn4CEQ3srCpfRvezvwwraWXc/xn3a5yjMQmz2HxTBbKEZ3Ie8IpSXA==,iv:4T7wI+inuA8MtYlW1QYdTGXuD/9OWGyTjzmDvIvEhMI=,tag:La/Chf0Ykast+Bgr6JWXMA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSlhLcGhEbTZLaENha2RZ
        NndnbzlYN2puWk0zM2x2K0xya2YrMy9vaWxZCkN2dkt1enNNRGhwc2xsbzArbm1Y
        amN3d2lIRWM0MzEwWHVDZCs0SFBLMncKLS0tIG1IeWY3amI5REFXcVdVdEIzd0VC
        bC9QcTFKcVlrSmxiRDhVUi8zd2U3L28KuFJzOc71grx6n7+QlYOpLwWlWBb+pFi2
        tUG9Bmadm4b7JjZybvGtcW0mHYWZNmfY5xfEFOZh4kwJq31gM9LU6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-04-11T21:54:15Z"
  mac: ENC[AES256_GCM,data:4T0Nyzx/ZzUIsPfxz5rzzpGVgAR8OWHMVdJU2/d+d/7eI+XwwnO3yiqQ/xj6RM0/VoYJpZwFSzTLnRQxN1MwvD4cu1f0M5cv60tEEAGjMG1V8hSElkicIsJuG8kQrlrODrf8Hi3iSAeGT+F3MA//eIpK5yOTNDq9FtNQsbmPyaM=,iv:YHHVgkFhlWz1vY8KKjK+goJ5EK4S3pRuX1LFLGoVJWk=,tag:zj0PfjkxLPKjJewX7/oWvA==,type:str]
  pgp: []
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: kube-system
stringData:
  token: ENC[AES256_GCM,data:EwP2tdAe2r3BoWrxtLl28xPbDILJhQbbSkt7CNXF4t46SleiT6ZWYciMwHYejSCr9so3i1NAuoV//v+wWp6x2bdCCPBw4Cii6xpYnr+xiuRiIqkLIIYW0uIzPypriJOcOdfjAMC6fHUaf0etUFBf7LuYx8cm98os/gXm5b61aQH4O17GWsFJWQrJkvzHBhciVX0SOH2zhuHpKsCmU9auyQ3YescN0qeuXRjx/RCJ5S9a3IpEUslCooBx7bzHvpYN96UWXZEUj/AJCJSwITpjA2UKmOn2EIBylIsp7gHB+p1qZ0u9OLSX35E5fRvlvv9ysuuneAa9+wERVvV9pedNM2drKigVIn6CeDPnsuugMxOdEU2M9E6NSM5+Ce26CU9IojtzkJ13EDOm5bS+CGrxlzkqQXLF5TYVB1WawRzQtFMO2Fum1AqtOShMPMDmI9ZZhmTL+zJcbbqjJ4GgwpplrwRAgMMCyvLGECYALh+z6IyrfG9nCxRXTjNrqrV6AsxnxDOHMAb2t9LVfXDdZNgo3Xa+QmMlcN+gDkp+b2X/WnF4mT9JeMEe2sTtiEZFVQjfBMAj7oACO+Vrdw/MoewxuLSWJtTur9oY8015aM5SS1+5YjizJnzpXifD6hiLWicvFnUD5hUjBBATeIbBoF7GqETHKZNl51ip4dSA3+IIn+noeuiqurQ15MPZjcXkZJdal3ywzz2k8DKL/ASMVKLLa5IdiK1jaYOLXrzKQO4iiMSNMxIrfrlGVvTpOEvr9pxa6h64QB2mnFpYLV9V1P4WbriTiM8qulT6r3ZftEj6AXy31qtAHgTcWAqjD7Sfx4yFMwsg3YhDH4tt8mzyN19tJj22,iv:/UEioxyomU5faIV8VeIjW9WANaQlWUBraKZxxVNmm1w=,tag:kESabUXuH7CxMkcbK1QU2A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSlhLcGhEbTZLaENha2RZ
        NndnbzlYN2puWk0zM2x2K0xya2YrMy9vaWxZCkN2dkt1enNNRGhwc2xsbzArbm1Y
        amN3d2lIRWM0MzEwWHVDZCs0SFBLMncKLS0tIG1IeWY3amI5REFXcVdVdEIzd0VC
        bC9QcTFKcVlrSmxiRDhVUi8zd2U3L28KuFJzOc71grx6n7+QlYOpLwWlWBb+pFi2
        tUG9Bmadm4b7JjZybvGtcW0mHYWZNmfY5xfEFOZh4kwJq31gM9LU6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-04-11T21:54:15Z"
  mac: ENC[AES256_GCM,data:4T0Nyzx/ZzUIsPfxz5rzzpGVgAR8OWHMVdJU2/d+d/7eI+XwwnO3yiqQ/xj6RM0/VoYJpZwFSzTLnRQxN1MwvD4cu1f0M5cv60tEEAGjMG1V8hSElkicIsJuG8kQrlrODrf8Hi3iSAeGT+F3MA//eIpK5yOTNDq9FtNQsbmPyaM=,iv:YHHVgkFhlWz1vY8KKjK+goJ5EK4S3pRuX1LFLGoVJWk=,tag:zj0PfjkxLPKjJewX7/oWvA==,type:str]
  pgp: []
  encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
  version: 3.7.3
