---
apiVersion: v1
kind: Namespace
metadata:
  name: downloads
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    downloads-routed-gateway: "true"
    volsync.backube/privileged-movers: "true"
