---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: esphome-secret
    creationPolicy: Owner
    template:
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .wifi_ssid }}"
          wifi_pwd: "{{ .wifi_password }}"

          mqtt_host: mqtt.phekno.io
          mqtt_user: "{{ .MOSQUITTO_MQTT_USERNAME }}"
          mqtt_pwd: "{{ .MOSQUITTO_MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: esphome
    - extract:
        key: mosquitto
