---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      esphome:
        annotations:
          secret.reloader.stakater.com/reload: esphome-secrets
        pod:
        #   labels:
        #     ingress.home.arpa/nginx-internal: allow
        #     egress.home.arpa/world: allow
        #     egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
          annotations:
              #           [{
              #   "name":"multus-iot",
              #   "namespace": "network",
              #   "ips": ["10.100.30.234/24"]
              # }]
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.100.30.10/24"]
              }]
        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2024.9.2
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1
                memory: 2Gi
              limits:
                memory: 4Gi
    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: esphome-config
      # secrets:
      #   type: secret
      #   name: esphome-secret
      #   globalMounts:
      #     - path: /config/secrets.yaml
      #       subPath: secrets.yaml
      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
