---
access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks:
        - 10.100.0.0/16

authentication_backend:
  ldap:
    address: "ldap://lldap.security.svc.cluster.local:389"
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    group_search_mode: filter
    user: uid=admin,ou=people,dc=home,dc=arpa
    password: password
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      member_of: memberOf
      group_name: cn
  password_reset:
    disable: true
  refresh_interval: 1m

duo_api:
  disable: false
  hostname: "${DUO_HOSTNAME}"
  integration_key: "${DUO_INTEGRATION_KEY}"
  secret_key: "${DUO_SECRET_KEY}"
  enable_self_enrollment: true

identity_providers:
  oidc:
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        public: false
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET_HASH}"
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - groups
          - email
        redirect_uris:
          - "https://grafana.phekno.io/login/generic_oauth"
        userinfo_signed_response_alg: none
      - id: immich
        description: Immich
        public: false
        secret: "${IMMICH_OAUTH_CLIENT_SECRET_HASH}"
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - "https://auth.phekno.io/"
          - "https://auth.phekno.io/oauth2/callback"
          - "https://photos.phekno.io/oauth2/callback"
          - "https://photos.phekno.io/auth/login"
          - "https://photos.phekno.io/user-settings"
          - "https://photos.phekno.io"
          - "app.immich:/"
          - "https://photos.phekno.io/api/oauth/mobile-redirect"
        userinfo_signed_response_alg: none
      - id: gitea
        description: Gitea
        public: false
        secret: "${GITEA_OAUTH_CLIENT_SECRET_HASH}"
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - openid
          - profile
          - email
        redirect_uris:
          - "https://gitea.phekno.io/user/oauth2/authelia/callback"
        userinfo_signed_response_alg: none

notifier:
  disable_startup_check: true
  smtp:
    address: smtp://email-smtp.us-east-1.amazonaws.com:587
    sender: "Authelia <authelia@phekno.io>"
    disable_require_tls: false
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: p_session
      domain: phekno.io
      authelia_url: https://auth.phekno.io
      default_redirection_url: https://echo-server.phekno.io
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.db.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.db.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.db.svc.cluster.local
          port: 26379

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true
