---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      calibre:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/calibre
              tag: version-v7.7.0@sha256:84d434018691fa9af36a7629a72f0cc886885f2c0bbca645b2e307d85abfca2e
            env:
              TZ: "${TIMEZONE}"
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 15m
                memory: 324M
              limits:
                memory: 604M
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
      content-server:
        enabled: true
        controller: *app
        primary: false
        ports:
          content-server:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: ClusterIP
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      books:
        enabled: true
        type: nfs
        server: 10.100.50.5
        path: /tank/books
        globalMounts:
          - path: /books
