---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre
  namespace: media
  labels:
    app.kubernetes.io/name: &name calibre
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
