---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netboot
  namespace: flux-system
spec:
  path: ./kubernetes/apps/home-automation/netboot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  # postBuild:
  #   substitute:
  #     APP: *app
  #     GATUS_SUBDOMAIN: *app
  #     VOLSYNC_CAPACITY: 2Gi
