# https://external-secrets.io/v0.8.1/provider/1password-automation/
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        POSTGRES_PASS: &dbpass "{{ .POSTGRES_PASS }}"
        # REDIS_PASS: "{{ .REDIS_PASS }}"
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: smtp
