---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"

        AUTHENTIK_EMAIL__HOST: "{{ .SMTP_HOST }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .SMTP_USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .SMTP_PASSWORD }}"
        AUTHENTIK_EMAIL__FROM: "authentik@phekno.io"

        AUTHENTIK_POSTGRESQL__HOST: &dbHost postgres-rw.db.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: authentik
        AUTHENTIK_POSTGRESQL__USER: &dbUser "{{ .AUTHENTIK_DATABASE_USER }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbPass "{{ .AUTHENTIK_DATABASE_PASSWORD }}"

        AUTHENTIK_REDIS__PASSWORD: "{{ .AUTHENTIK_REDIS_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: authentik
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: smtp
    - extract:
        key: cloudnative-pg
