# https://external-secrets.io/v0.8.1/provider/1password-automation/
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres_password
      remoteRef:
        key: authentik
        property: postgres_password
    - secretKey: authentik_secret_key
      remoteRef:
        key: authentik
        property: authentik_secret_key
