---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.5.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
    # initContainers:
    #   init-db:
    #     image: ghcr.io/onedr0p/postgres-init:14.8
    #     envFrom:
    #       - secretRef:
    #           name: *secret
    replicas: 1
    worker:
      replicas: 1
    authentik:
      worker:
        replicas: 1
      error_reporting:
        enabled: false
      log_level: trace
      email:
        use_ssl: true
    redis:
      enabled: true
      auth:
        enabled: true
      global:
        storageClass: local-path
      architecture: replication
      replica:
        podAntiAffinityPreset: hard
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    envFrom:
      - secretRef:
          name: authentik-secret
    postgresql:
      enabled: false
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: authentik-secret
    geoip:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
      hosts:
        - host: &host "auth.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    resources:
      server:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 800Mi
      worker:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 1200Mi
  valuesFrom:
    - kind: Secret
      targetPath: redis.global.redis.password
      name: authentik-secret
      valuesKey: AUTHENTIK_REDIS__PASSWORD
    - kind: Secret
      targetPath: geoip.accountId
      name: authentik-secret
      valuesKey: MAXMIND_ACCOUNT_ID
    - kind: Secret
      targetPath: geoip.licenseKey
      name: authentik-secret
      valuesKey: MAXMIND_LICENSE_KEY
