apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:RUCvfQ8oUrjkKdi4kTCPtB6TGDrHZazdUyCEhBJuA0e1tN9VqDPM1A==,iv:Hg+SlhaX/JtkZllqht14amDNcLg74gSXiEhj2cXMCbU=,tag:DcsdavADqVWxcvkjMlUEcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aW0yMTNoSlNteFhjWFJP
            UERtb2R3dWN6MTJJZjZqcko1dnE2dFZnM0I0CnU1azA4T0N6MTZhMC9Sa2x5M3Nq
            b05oR1Y3b0pzL2R3d0NTeGZINFFvWEUKLS0tIEpUS0dzUWtsb09HT0NlS0IzOG9t
            YmcxejR6bEwzREp1NUpaZmNFVTc2VWsKiyAd48N6w0ITxNxMSqTRa7KecsQXGdFu
            UHth4+d9AiglGlHEw+0ZEeXqOT6R3E01rcQ6jiDQdYPSrLGgCvkpxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T02:07:47Z"
    mac: ENC[AES256_GCM,data:pFncz6757Ci0xctPPEi10e+eCoOVI5EZqhNIACREoGTdtnr+Gdjg8ArB9RbHOi1MmRrqWXCCSDwnuR9iHXNFJ2fZM3/AhOnXyG2cIlRruZOPWGNSm0yXXORqpjglIm4Q8oxzL/DpkRA3kLbHrVrT8AN6fjcGKhc+TBwO9+Ka3+g=,iv:MKcz0RIgB5f+KkcBjfRVGIczetg4gdAVRuEL53L7m2I=,tag:AiurLSmXVZEd343xdGl9Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
