apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:kXX9hisdiUkjUVn+1LO7MMXAN0IrW4VOXZOZjTiGT+Lul1aZzA==,iv:6pJFMJJIfJRSV7RdaVvrSlFKlB2ZM89dnoCidFlUt6I=,tag:AQ0ajxKMEdSPzRs5jZBdMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YTB6dzRuWUtmTWc0ZEh1
            L3A5b3g5UjArcFkreFp0MWcvZGY2dG92MFZrClV6T0NjWmtKV2Zoak1VZTNHQm5P
            Mmt4aDZiYVVBWlQ0TXZQMUQxbHc2OWMKLS0tIFBoakxDVXJiSUFETEZXMmRrZTJK
            NDJWRUdOZ1lJSFloRi9Db081Ykx1NGcKQNWNCda/LhCrOU3wzIYJvoc4cp7LXqpI
            /WNCNxbq2WWlU+HW8TwbLvZLIL3nmrf/XZdCKvqPucfQYSKH94+WPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:49:01Z"
    mac: ENC[AES256_GCM,data:+xS7f3R3Sl5u0yWQEWWk5+aF46RydwCvTv8ZSY2DhK5XPgHQUwPgWHnN3eHmF11T54dgZ0i04twDJppxsLVrn74CuemoNnBg3bOtZYMdyr39iuhQJcngo4oOJRtEdeJ+Sm5XDUCZFDm5eA9GPsenKV6YumvFrkjQDk1fuPD8WpQ=,iv:K+w8tzyksctWnwh98cwDeSVqsX3/cG3jNlRuaNw467c=,tag:Ec2ACI+m3DE7JqBsglq+wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
