apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:moX1KFwiNMsy2gkx+Mr8CkBtEjBlZQ0V/0MyoJgl+Mb2+1P+e2wi9w==,iv:Dr5RoP9QlctKAbIMvIthmB3UcyovscZa0Jy+Ka8vpaA=,tag:lfWnTLZ8rA1JQytTIn4ddg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcytCSTFwRDFGcTNqallp
            Rjk5NXVEeGJXRnUyYk1VWWxJRVl1cU9kQUZFCmZ1S1hNMFpJTThSbkhBb21IMTNE
            YjRXMkE5UXQ1OWZEcktvR09XMXJBWVEKLS0tIGhzU0QzUWRjQyt4T1owOEpSQ3Fo
            Nk5aVVBxdXpoKzk5RmcyWURxU1RKek0KpFkqVdrDnmRv9fHE7fK+/WximksjAu+T
            5PFRSPetNMks9Ww5lokwmLRg51tfhPvO/Q04xnkH3D7xJc/Lsaip6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-17T02:39:26Z"
    mac: ENC[AES256_GCM,data:y9VRTM7p68MqOnVKYxAi4mZ4elr8z29S8+reFiWJe0mPk9UycSfKCJpY1DiuZvt/OnZRrDvtcJYe/ImYKppiyWtrtcZaUvXZE/bZLmEQSzqNEZPzEW8bvz1FKlkPaCqxMcDh3KhukIrJR1v7ZH8kgQgk9lKkS88gOStGaII12Eo=,iv:vwoSUuCg2Eb+ZUpa+wQcFEZg2K+EUnunXr8G/F1m2FY=,tag:4/Q7qU9xMYF0UhpV0uYfVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
