apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:vPY+RyUBS+dO5rNSh3oWOZrD3OM6hfs2NoQHs1LYdY0dUyofbvqPsg==,iv:G3c1Gk4gmCT4w0d7LgC5TQMFuQZvlB68pm9hfXO8/Nw=,tag:B6gLHLGB7e4cl2TA9A4ZmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjb0k4VVdHZzQvMXh6dVFh
            NzdYQXVTY1R4aHBCaVNoY3h5T2E1QzA3RFhnClRvT1JjTVhNQ0UxSEtMMWpsNFF6
            R1JXb3pXY3FxQkhzRHNicWsvMFJMMEUKLS0tIDB1ME1UTm1PVm52dEUrWENtRXNq
            Q1h1WEdnaVdvTVNZN0pPUEhubTFLbUkK7YV6+wzyMV3ztRJhoUU2lQ4YH5paZaEp
            9xroiVfccR2yIDqGjQ3XLTD95T7wIT4vGB/s8aspULEUcI7gtokIrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:50:47Z"
    mac: ENC[AES256_GCM,data:6jCQXm4o3UoHChfUeZ0086X9KJtNKdXC+DxogkO6rwNy/LSNV6zI3C7uuvhusUaJnwdedoxVD12JLsAovnsYHvholtctigwmpB/2u/QvLezGRu8H76+p26rZ3c1xWTEQwt5y1LDmuMxXMC4xoEUfjPXQ4BtZAllIhtb3CVCXiW0=,iv:51YYn7elkjE1wh8p/+KjoNMKW1zTPTcQohBdeQQCpAA=,tag:mt2KcBt8HjvBQyOBFSJ9Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
