apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:RTy7e4L1rCkrkYUZ9pEHhgkmpggHzwa5L2oaddgzWlW9mRnTCQ==,iv:5CmARNSpaTVunfGyCJ2AgGzbPiNr3Hxqd/7I+jhLVmQ=,tag:IhT3wDMksoqLCsttRuN25A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOU5jSzVQQnduV2kvVW5F
            WmJMV2ErYlowSTF3NjVMd0FITzhhdDRWK2xrCmhOWFRsTk9HQUxBT21DbzVVYXVs
            bG9Wem1XdFBFS0pHZnpTbGc3ZDJJS0EKLS0tIE5xTHpPSDBUUGp0YWxLSW9GdUdI
            R1d0NnloK1BqMkxQcTl4YmU0dnQ1ZjQKih3TiShJMUjiHcaQdzaFM1B9pZddt+v8
            K/lYuCxDI2YwPkt9f5lssPGiLef+APmOd9rKbKcNFOX7Z1edRNZvZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T17:22:38Z"
    mac: ENC[AES256_GCM,data:Z2DnzFQG/eaBfQYsDBOBsLNPhoGWxzMuDu4R+vW3Q9kisohaCiV8abjXBwu/tAGTwQJ+2qmdYcsdOjqODJrDXEH45zlGEq6b+lcIqkjGPpsAZXaHakqHu/LBdBsjJrPZQBy1I2PXlfq79Ww+Zpi832pXYLdwt8W5gxmAnn8yRZo=,iv:cQSs+8r4TazsvSAycJEc5x1SrVrzHboKw6lySkjXk08=,tag:ufruTAJ9CJNy1JxPs9rZgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
