apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:dFWY/wrnKEkeInLO9S73Es04uKYUOgqWbAd13jjo0NOIr3nvlfW+IQ==,iv:UItaG9rtNK+q/Pz8infgnbz25gHpF5nUFyjcKSRtVNo=,tag:nCozcrFlfz8BQsddbqRNzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M1RpU2Y5cUFHR2xjQmJp
            WERsaFlRSEtMVGlRYkVqMktaUVkrTmlrZ0cwCjVQaTFtVzNzOGlodnoyN3FxYU1R
            cWw4N2V4d3dLWXlncUNkTzVSK3A1amcKLS0tIGx6YjlvRlYvZGFOeURMNWtaQUpl
            UHcwQkJBK0VRV2x6SnJMZmw1M1F6UFUKzZU5WgeJFgrFdCheeMNsZYZO7pkhtzhQ
            GvR5/Ua8DidOTPhTp8Jo6Wvrl2Lnn/mxou6602+3Ey24cItsIivOzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T21:41:05Z"
    mac: ENC[AES256_GCM,data:QdNrWmF28KjkisdD6+pLAoJZfHH6eSgRgLC5PlxW73z81Uh4Hw5jq453VhiIHjeG++OikE8Hud4tgimyoPQIN7ly3U95T6Vq8cJqluE6/arY/7VvIQW5nFaa36fc8U7kRrVpfi2PEvLTi7kjROJSv1hWGeBdyoF096dkNpMIvdw=,iv:wFjG1spGK2PDPDyA6PgtLdJA90As/KH6BAl0rjJeEFc=,tag:vl2s14CTKZ1bbL/8EG8rzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
