apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:QkgXJgklsc81Ul+jy5+P0FMT+wwy8rsNBAez5qdtFw0FFSHJtngkyg==,iv:gIY6WN2EclOdDu7+RH4XmqkQh01+4p38zpB2wYlJWUw=,tag:Ajl6Uxe/ch5wV7H3jicqJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MEtFSVExTWJzMHRlMVBh
            R0t3RGJrUExKZ0RQOXR5YTJIeW9RZnlpRGpjCk41TG1vdWJEUnRpSUNQOG1iVVVM
            SURMT1JDWEdxaFZVNFA3MDhmc2l5RTAKLS0tIEZqdSszYTZ3M3ZhL1RjeGgrZkNa
            VjYxNzY2Tlg3dHVKMXY4TXQrNUNjbTAKTD/cULJ5OaVs5V+kFFskoc8PupvIRzko
            pJI2PCYFbTj6lG2GmPWqYhgwvFquuO9URl1BTrOP+K30acBZGwePMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T01:41:47Z"
    mac: ENC[AES256_GCM,data:Iq49QQHeAWRpnf9EbD5SoO9VL9d5IZcmQPya1qDf9pn+pj4XsfRvkwqk4vznqm+zmMA9durbIXmCJcaz8fneNjSFaVJs8F0d7L9IDgA//jkhNnSrQ2M0HLikZ7j2+J5Krytpp0KgVCEXtIRhQRMHvoGm/ouPROjgHPB8VGp6/lg=,iv:G1o2re1guTXucPML2iP9+Zezo2ev+TFDZi9R23vA6wU=,tag:hTGdv5UvB1rwxOIxIs0lMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
