apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:0FG/6VUOPg/4cGljJQHDejvrRVpGhbHSbbqjZ9FnWOyNYeh4Eg==,iv:KLgOtBMPecGQbhA5ZNWR5OEvCzizfkwlHsRhFimbYg8=,tag:PdupdFttcmVY5WD/Td6TRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T2xVZnFZRkxEM1NsN0ZY
            MEZub0M3ZVI3N2lINW1td3ZMeTljUTJLa1VjCk1tNHNuNHQrcWYzeTh5MHBsL0p4
            OHUwM054aFEyalkzV0ovSUZ4REFKMncKLS0tIENWYlNPNXlaYTIzcDh4NmVlY3VT
            WTNlQmNEanVCVDY2VEJoU2IxdGVzcjQKeTTDxAhD5Yl3uZrfiVoimhLj2Ir7AF7W
            WUkv/l5k+SLlnWJImGf5+OeVjxjzmxZ7zTX60MJd8GKUxD3OkkGUgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T03:03:09Z"
    mac: ENC[AES256_GCM,data:wxxRN5rbRo1kcVzcK2T3DIBHub9Hs1uL+SZrT1aqlRZej1/yVkLhgvfQGVZfakBAPt4u44hDty/J/FUOKslBtInusf9OJIGSwvpR8krGyHWRnxSOCog4jy3pPyZvfBkZaN1BLNS350PH6N0+PjxvkiPjJ1gT2THdUMk9rH2bQCs=,iv:C2Vz3LunFMVy92IBDF++0isZIhe9SsmZEIw6mFeDdJQ=,tag:lLPusp9gXTLULiUV6b5SXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
