---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: media
  labels:
    app.kubernetes.io/name: &name immich
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: longhorn
