apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:qEi2k4qBYvtpgsP7NHyg8w==,iv:VePUENuuGAQbVrTaXk1ae4Xff4VMt5bsYOHWnYn7Rh0=,tag:gCRvL4OFpyXdAOKl4bBv8w==,type:str]
    api-key: ENC[AES256_GCM,data:d7aV9GlCnMB4Kvp4Vu1O7AFeTo9QsshHnzH6G4/M+AZVD7Afbw==,iv:r3JBSu8BITnoqDEX2N0iYoqQ1aId9aRZE63izSnQOjs=,tag:0blCemBpKRcHxFXpDyRYHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrajhDWGdZK0dHRTczNzVO
            Mk1ocWhyMlB4dWNBSlNJRUZpTWFReDBISVRFClUyVXhNVnozT3Z0bHVlTTE0OTY3
            d3BSQmpHR01yN2I3QUgzZ25icC95TmMKLS0tIGJjYldVZ0RDdmRoRDhjV2JQYXVl
            VFFlNS9YSFRqUTJNQjhoaWxYMWJYYXMKBQf5S7V731M54r0IbBN8+Y3DV2x5OD5g
            hXWAm0uV0iezuQSFY8UabS1Ny0Yr7+xPD5APa6RjuUltCqLLaZvzyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-02T02:24:54Z"
    mac: ENC[AES256_GCM,data:dgedkC++xkPSCag/UZ3IAsnRx/tRAYOh5jsXZ2luZItHD7jQMrkHEPJAXkxUtyPez7fV6cVYAlgSzsfPZj/sgvdr1I8cVU4CQ56TUReNdmLw68cDjvTekuuNJBSvlG1BEtiz2Wsa1vpFRZrGPSUFpPyPHsRg6nImZ5IjZbwEXjk=,iv:+KZEkSy++16TwJRy5B1+eY2IEhCZQXAX7rWoUzMrNhk=,tag:WbrpR/JGpQQgRamXgMHVxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
