apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:M6tc1Qi0A1CDwINkFQNRzA==,iv:utL0LawDrKhZMtZvLor2ydjYCvAhUbs+Fch9M+mH5mE=,tag:h/2ftLdIzqKKKoWq8nGGdA==,type:str]
    api-key: ENC[AES256_GCM,data:CMM5pIbUtVHL/LQGy5kemBMms1N2/ouXt3iwBe62p89P7vMKww==,iv:CdRRrWBeG8gv/pvM4YpIgVBuNiCZDyW9LrwmKwKhRFw=,tag:qOWTEfhM7HS+Xw2nOky+XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQjU3MW5HSDhpRm05dG5Y
            RmtBRm1BRzdUaWcvcU9IWGtCM1BqZGFGSmo4ClZWbUN1UW55dEN4NGtUV0lNYUhM
            dkV0eGh6U0kwZithbjN2RkZaWnQ0T2MKLS0tIGl6YzJPMFczSTVCR0h6b05nb1NB
            cSs2dSszZ3U4S2RVY09QNjZ2bk9OVUUK7weYAyWq1a4z3f1QnbRsty3ZSn+ol4mT
            HrAClFGRDgWvgmQRulGjurPXaoTAP39WIoTiPMxKJ/wIf7AcEi8/fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T03:03:09Z"
    mac: ENC[AES256_GCM,data:STuQIH0NU29nxle8926ZbndQkqY/l2au4c6ORAv2k5VNdtjSo6rk3hBgVb8CeykF80wSTRNY18tq7ZUHAOWQ238fSlC3EuvMyTtpzWHwmvj5wY3H6TDj78w26+ZreGtEODoEsmozNsV7YIKwHlG0yG+lGno/8swQG7fFXYpbm5g=,iv:aIfCYF1tKLX60YVpTw536hDyQIVNMSRJMWMn/+1BhcE=,tag:lfg5JDhoVpF0LjinAxOXHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
