apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Udc2jBCZpwU0D8ueIDGYkQ==,iv:inLF8XvAlAihOXk+hG780orVukkmyxRZhOiTPKD4ET8=,tag:vY/Wl/Dy+OApuPl0k/nRxg==,type:str]
    api-key: ENC[AES256_GCM,data:5XEWFjmq+Gbp4s4an/jbthngb9P/AMxJM644aOeQNw8dMACbCQ==,iv:+vN6bWqEAm1v6zUiuhcfMQiwQ6P+PLZ2+IOA+L+BhRY=,tag:TCKSbjpTz1213JnqdQD4YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadEVSMmM5MVNlc3N3cGxn
            eFRuUUpCZmpIeUgrWDhldUxhb2dWa0U4VmlnCnJ6bE84L1FLc05ZK1M3Yi9XWUJi
            U1h0UllQUG42cmZkbTdSQkJTbTVoV3MKLS0tIGp3UVI4VUJ2UHFVYmFITVNpT3Vn
            MEFsRHJDTnB6TUVDak01ZWdJbUlQbWMKNgDM8KdYairHTDtZGFrnMfiSvMBulGvZ
            gIGC3FHNzGmzP/QB5+3WBR4ZEYAlBwPw+SmoQhz0DQdkX8DTd/hlzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T21:24:29Z"
    mac: ENC[AES256_GCM,data:x5EzQG2T7RvcH8O1Fp9oI6BTBnr6+yNjcAbDJXidbhDmIKk/OIkrg2mWzE8LnofcU3tYvSLZ7XGiLZW/7Ube9mjT0a02qRwTDOp/RDsgEVwhzrooaOZGMRACN64OtNz9Y5L4ikxP1efho+nQMrA6Si3/KIeGVDEzUWBfpVxbUwA=,iv:za7zEOQrz/7zo50qCrLIEshvI4Cf+lVq/i9s7mlm3Tw=,tag:YDr48V2VjqEu4LKjOhka0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
