---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netboot
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: 0.7.3-nbxyz2
    defaultPodOptions:
      hostNetwork: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
      web:
        enabled: true
        primary: false
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_NETBOOT_ADDR}
        controller: main
        ports:
          web:
            enabled: true
            primary: false
            port: 80
            targetPort: 80
            protocol: HTTP
      tftp:
        enabled: true
        primary: false
        controller: main
        type: NodePort
        ports:
          tftp:
            enabled: true
            primary: false
            port: 69
            targetPort: 69
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host "netboot.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: ceph-block
        size: 10Gi
        accessMode: ReadWriteOnce
      assets:
        enabled: true
        type: emptyDir
