---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./esphome/ks.yaml
  # - ./firefly/ks.yaml
  # - ./home-assistant/ks.yaml
  # - ./home-assistant-code/ks.yaml
  # - ./mosquitto/ks.yaml
