---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dragonsfire-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    CF_API_KEY: "{{ .cf_api_key }}"
  dataFrom:
    - extract:
        key: minecraft
