# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dragonsfire
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.23.2
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: storage
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: dragonsfire-secret
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java17@sha256:c12ce9696a8fbf5bcddf631929b717428d41e63e7ffe0d522658f20eb5cc7977
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 8Gi
    securityContext:
      runAsUser: &uid 1000
      fsGroup: *uid
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: ${TIMEZONE}
      ENABLE_AUTOPAUSE: TRUE # Doesn't work in Kubes
    persistence:
      storageClass: ceph-block
      dataDir:
        enabled: true
        size: 20Gi
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: &host dragonsfire.${SECRET_DOMAIN}
    minecraftServer:
      eula: true
      version: 1.20.1
      type: FORGE
      overrideServerProperties: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      gameMode: survival
      pvp: false
      onlineMode: true
      whitelist: "phekno"
      ops: "phekno"
      motd: "Dragon's Fire!"
      worldSaveName: vanilla-survival
      viewDistance: 12
      modUrls:
      - "https://www.curseforge.com/minecraft/mc-mods/dragon-fire-mod"
      # spigetResources:
      # - 36618 #Prom Exporter
      # - 18494 #DiscordSRV
      rcon:
        enabled: true
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: true
          ingressClassName: external
          annotations:
            external-dns.alpha.kubernetes.io/target: "mc.${SECRET_DOMAIN}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
           - name: *host
  valuesFrom:
  - kind: Secret
    name: dragonsfire-secret
    valuesKey: rcon_password
    targetPath: minecraftServer.rcon.password
