---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-gatus-ep
  namespace: downloads
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: sabnzbd
        group: internal
        url: https://sabnzbd.phekno.io
        interval: 1m
        client:
          dns-resolver: tcp://10.100.50.2:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
