---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.3.3@sha256:4ad73733ae11eb03852ba99d6e49bff93f8087f9f77b9b193a1063c3f6f31482
            env:
              TZ: "${TIMEZONE}"
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.default,
                sabnzbd.default.svc,
                sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local,
                sab.phekno.io,
                sabnzbd.phekno.io
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
              limits:
                memory: 12Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: ceph-block
        size: 10Gi
        accessMode: ReadWriteOnce
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: 10.100.50.5
        path: /tank/video
        globalMounts:
          - path: /media
      downloads:
        type: nfs
        server: 10.100.50.5
        path: /tank/nzbget_downloads
        globalMounts:
          - path: /config/Downloads

# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
# apiVersion: helm.toolkit.fluxcd.io/v2beta2
# kind: HelmRelease
# metadata:
#   name: sabnzbd
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: app-template
#       version: 2.6.0
#       sourceRef:
#         kind: HelmRepository
#         name: bjw-s
#         namespace: flux-system
#   install:
#     remediation:
#       retries: 3
#   upgrade:
#     cleanupOnFail: true
#     remediation:
#       retries: 3
#   uninstall:
#     keepHistory: false
#   values:
#     controllers:
#       main:
#         annotations:
#           reloader.stakater.com/auto: "true"
#         containers:
#           main:
#             image:
#               repository: ghcr.io/onedr0p/sabnzbd
#               tag: 4.2.3@sha256:fa8ddea45e56b0e36454c3c0eb30ff5521d90aeb5b35301656ae9236680be3a9
#             env:
#               TZ: "${TIMEZONE}"
#               SABNZBD__PORT: &port 80
#               SABNZBD__HOST_WHITELIST_ENTRIES: >-
#                 sabnzbd,
#                 sabnzbd.default,
#                 sabnzbd.default.svc,
#                 sabnzbd.default.svc.cluster,
#                 sabnzbd.default.svc.cluster.local,
#                 sab.phekno.io,
#                 sabnzbd.phekno.io
#             envFrom:
#               - secretRef:
#                   name: sabnzbd-secret
#             probes:
#               liveness: &probes
#                 enabled: true
#                 custom: true
#                 spec:
#                   httpGet:
#                     path: /api?mode=version
#                     port: *port
#                   initialDelaySeconds: 0
#                   periodSeconds: 10
#                   timeoutSeconds: 1
#                   failureThreshold: 3
#               readiness: *probes
#               startup:
#                 enabled: false
#             securityContext:
#               allowPrivilegeEscalation: false
#               readOnlyRootFilesystem: true
#               capabilities: { drop: ["ALL"] }
#             resources:
#               requests:
#                 cpu: 200m
#                 memory: 2Gi
#               limits:
#                 memory: 12Gi
#         pod:
#           securityContext:
#             runAsUser: 1000
#             runAsGroup: 1000
#             runAsNonRoot: true
#             fsGroup: 1000
#             fsGroupChangePolicy: OnRootMismatch
#             supplementalGroups: [10000]
#     service:
#       main:
#         ports:
#           http:
#             port: *port
#     ingress:
#       main:
#         enabled: true
#         className: internal
#         hosts:
#           - host: &host "{{ .Release.Name }}.phekno.io"
#             paths:
#               - path: /
#                 service:
#                   name: main
#                   port: http
#         tls:
#           - hosts:
#               - *host
#     persistence:
#       config:
#         enabled: true
#         existingClaim: sabnzbd
#       tmp:
#         type: emptyDir
#       media:
#         type: nfs
#         server: 10.100.50.5
#         path: /tank/video
#         globalMounts:
#           - path: /media
#       downloads:
#         type: nfs
#         server: 10.100.50.5
#         path: /tank/nzbget_downloads
#         globalMounts:
#           - path: /config/Downloads
