---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name sabnzbd
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-restic
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .BUCKET_NAME }}/sabnzbd"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: sabnzbd
spec:
  trigger:
    manual: restore-once
  restic:
    repository: sabnzbd-restic-secret
    # Use an existing PVC, don't provision a new one
    cacheStorageClassName: longhorn
    destinationPVC: sabnzbd
    copyMethod: Direct
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
