---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "phekno-io-production"
  namespace: networking
spec:
  secretName: "phekno-io-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "phekno.io"
  dnsNames:
    - "phekno.io"
    - "*.phekno.io"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "phekno-io-staging"
  namespace: networking
spec:
  secretName: "phekno-io-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "phekno.io"
  dnsNames:
    - "phekno.io"
    - "*.phekno.io"
