apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:43v4FR8xlnObcWOZSmiYNh7XO+bA+xmiFEXVS4NN7ehmIuEDy65OCLynlUlYqQU2C0wXONJKh5S9yIOo,iv:n2hj57oAMlf42pILGpYo/Z0MPoua/ck3YW/KrSx8Lzo=,tag:Acx0duNYm53LB47q1pKErg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRy8rRjd4dVJzR2xMdWlk
            cUdCK2pXQWlIRkdkK1hUeGcxRE9SNmlTaEdnCitYaVJkY2E2ak0zMC9CeVpaaE90
            YnE2MG1vbkNmVUExNlgvQUNzZVUrMTgKLS0tIEsvTWFKWC9CdTk4REtDZzBFOEV5
            ZU1mak1kM2toekF2MXFJT0R5KzR0K3MKWbQo2p4Y4JzZgBbSkbiybO5i7Z+Uc0iu
            dkzI2nKpa7yI3LvAoM8QN3XIiOb9O7oQu0ZXAktxGRd6euzmS/uppQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T13:55:03Z"
    mac: ENC[AES256_GCM,data:urs4ZuZYxQ1uhGmT3gFf8/EaeNh5rG7hFgIyYeZahKhR7ibRsi4qW+soHycAieimlHUuz6vqEKGEPHk6Eorr9dn2Zmap6bJMTRSxnpviJBPmTRtodGRtAhXHS8PysWe1yfssFPKi56SNrSafzqPSZmn+Y9q3kfLAA8L/IiYezDA=,iv:kHvw269uJe01qC2vLITbwbFFDwN8qagFFR48iHyg3oQ=,tag:ZuNH1gPiGDF5cqyo12UWEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
