apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gWUPr6M=,iv:QZ5PmctDaoVwKTzZqr4VPreBSKdo6Zr+VuARLyqm27g=,tag:bqOi0XExuPhtnr4plsk+qQ==,type:str]
    password: ENC[AES256_GCM,data:UeO9BTXT5ZmKGy73Epwnv9Gwh3VbhcPWLVeu6qIgi0W5XP6mP5mVoXxvrV31aUv4bYyQVv0amFlzamtF,iv:PzaF8AWOdfOb6OTXuNEstBsLrbjBDj42uVMkggeG85Y=,tag:DuBaxx5H63NtMhxH6z6n5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWml2S1hvZlI0c3lLQW9w
            R0VIUkltVVNkeExwdTQ0cFFuV0lwUkQ5Q0VnCko3ekExNDZ6NmRCeXREc1VDTVM1
            SWY2SjFwYnJ0SGdMOGdhWEhXakt6N1kKLS0tIDFDSFpGeTV1enNqNjlmT0hlQmdz
            Njhudmp4MUorSXhuRUhJN0tIdUF1NncKeuiFA9qozoXmOrVULJLgDjIvS7n53wuv
            NdHCWEX/dNhxFgAGiuFedKjqspWiiKMe0WNL4Yh/tuA1Nt4q6+LM1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:36:04Z"
    mac: ENC[AES256_GCM,data:Y/2IvICPl55Y7gRNcF44mrSX10culW3hF3lJNXujaWxfUu4GQkyqVVbMxamRa91kwb54LOXMw+SBKeAUzIXY0vgWXCdL688Cmw6K0mqupMFyYN/sRHv9xOd207EQX9rzgsJg9ZVVejaqcM5HzT3GvN7NcPrDDuyg+uYFVYX1s5s=,iv:6OqKZd0ADinlSjYkr1r5mi9c4+U3iUeDKTTeNdJ2B90=,tag:+IO1hASI3+G2mXawk7J7cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
