apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:SI2ApIM=,iv:ul6I3ho4HkNzNvzNTiGveMCLFelKvhhTZRBp62KtPyI=,tag:bWBgaLvKN75pAMHcgrI+Xg==,type:str]
    password: ENC[AES256_GCM,data:F+pQVzyL4PtgEexjE4D/q1wAzRittpFInMsaKRI5ZLCPtJnGUb0LLXxrDd79I76ubRQeJ94tbU8dDIAB,iv:SR6f4wH8B+vAMnu5ItvNoPsi/8AQ2Hl0nc2+CS8Yn1g=,tag:NIL6EKlepHLUNXKRg3/V3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXAzdnEyL01KOURZYXdM
            UUdaQ0tZZnpDd2h3bDRIVVI0Q2VkRUZQMldVCktCVEVjaWNSSkNmZm1NdEU2a25F
            S0ZKWXVnYWRqcVZZdTJyV2s5YlI2NU0KLS0tIGdhZnpzS2xreXlXci9MemVacStG
            bms4U1FGaVFWL3U0WjZtMnIzZHFLQ00KAYw/JDsuFDgvGoKkPJYMzYKa2xopxoDe
            rQVB+jWjrPd7hqqaB7D7rhpeyjjpNQLyuWDC/5srbipKc84JThWUxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T16:04:40Z"
    mac: ENC[AES256_GCM,data:M2F576pa2ayXtYAE5s4/uJyHT5BVaQOlWYa7WaEGNk9Fz63o24HKyfQRA5hy7WjhE5uiPoXwirl+YNYX5sNMRmpfxSOi4hARI9ExGHQd2NaGsCKIko4eWeHOOEnbZXpaRZbGGnGyuhaSqJKKCJivreYrUTpb1yztro//2dkwDsk=,iv:dvSZaO3AIhVMtvsKFSe2IOzpY5qpNJzCAlM+nOEZhvI=,tag:aOzvw+PphjwEtIzzmDXYjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
