---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vanilla-survival
spec:
  endpoints:
    - dnsName: "ipv4.${SECONDARY_DOMAIN}"
      recordType: CNAME
      targets: ["vanilla-survival.${SECRET_DOMAIN}"]
