---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-stores
    - name: radarr
    - name: sonarr
    # - name: rook-ceph-cluster
    # - name: volsync
  path: ./kubernetes/apps/downloads/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: recyclarr
      namespace: downloads
  interval: 15m
  retryInterval: 1m
  timeout: 2m
