---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app oneblock
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.23.6
      sourceRef:
        kind: HelmRepository
        name: itzg-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    # deploymentAnnotations:
    #   secret.reloader.stakater.com/reload: &secret oneblock-secret
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: latest
    resources:
      requests:
        cpu: 2000m
      limits:
        memory: 8Gi
    livenessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: false
      command:
        - echo
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - echo
      enabled: false
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      TZ: "${TIMEZONE}"
    persistence:
      storageClass: ceph-block
      dataDir:
        enabled: true
        size: 20Gi
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: &host oneblock.${SECRET_DOMAIN}
    minecraftServer:
      eula: true
      version: 1.21.1
      memory: 8192M
      difficulty: easy
      pvp: false
      onlineMode: true
      # downloadWorldUrl: https://www.curseforge.com/api/v1/mods/307740/files/5493721/download
      whitelist: "phekno,quinnyf13,harpyf13"
      ops: "phekno,quinnyf13,harpyf13"
      viewDistance: 12
      rcon:
        enabled: true
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: true
          ingressClassName: external
          annotations:
            external-dns.alpha.kubernetes.io/target: "mc.${SECRET_DOMAIN}"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          hosts:
           - name: *host
  valuesFrom:
    - kind: Secret
      name: oneblock-secret
      valuesKey: rcon_password
      targetPath: minecraftServer.rcon.password
