apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZvNG8OoV0XU822Z5pqw=,iv:L+jbP7/n74LpBw/awJ0HNGoMQllK8NKAIC1+aweIyyA=,tag:kiXjUXbNf+JA/Ue2zt3BTw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:CmGJeJESpGsleNH4ori7Sw==,iv:e1v08nYFDpBxTsmi/H5+OznNW92TegNj6pmhpc2Wgcw=,tag:ZpRrUecvrQupaCo6C9FBSA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:30ogcs3b09ZwXGRMOoOaEDfiCeqHoE9xSVrAdBfIIiacq0Du,iv:8efj+iJTqWw5Ai/JMrGDwKYqn+cpzILxtp5FOWqrSAk=,tag:XaXmzwrjEgRb9idB6upL6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUkMvNEUxeTJCbXhQSlhx
            TnZNUWJodnBReHFiWE9lbEZFMm5NZm1iN3kwCmxia3hPbnVCa0I0azVtRVRFSVJ1
            MTU5TjErdjdsaTBlOVIzeGllcUxZZEEKLS0tIEg0NDQ1aWZlWmZRdGVrSkM2b01W
            Rmtjb0c1YkxzZGZlUHNON3B0cDRUL1UKj+024BXGsxd8j59ayhCZLiCFKgS1kimZ
            80Nl8WZoxnKSsKmGRk/ANGcaRPliqZwXC2hGyq5rld1LYCKywSy6ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:50:46Z"
    mac: ENC[AES256_GCM,data:WrZYoo4eogrBHjMwvhhLt4nKLCndqhfMbWGKmk8jd0Y35usbMZ+kFHvSGOsy7Qfdo5tvXKrW102l0a+MYfu19LA7+MlDom05qU/S7MPBFEgm8BMwWMRM22dlm0BcRtiwbCgHSVLtWVCKu/N4fcNv4Esleu/EHXOgwdLXckGnRm0=,iv:wjT6yucsUmYMh8wEa6vsL/2+S2TZL4/nP7zNpYNjh+g=,tag:kZMHXeXzxK/sUY/X70lsnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
