apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2wq7/NKWNjud5HqD/g8=,iv:yDC+zigiL897f9Yurs3P4cjxJ60Nq2hEB2eN24ESTHM=,tag:bkhMFgQjoFv0aIlUcJ4wWA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:C53zoBDvVi+v2Cy1lXcQNQ==,iv:kfSdeufIyP9KM2M8p4HnLU+fvjlcH+Wqzrfo0oX9wIQ=,tag:oM0+nxRhe7/VOfYQs3zdQg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:htsZ7sXGSIU7pcN5miJX1JzDnysaZQYxZIJxsDwwNk5pIU8S,iv:c1s/suT7DUCZ1Z9VenfjLw465keMz29j6UdX58ELTkU=,tag:ZGFIpSYwuNlythQ43jYdYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVldLNWFrTks2RmhwcXVW
            Vy9FMm45TGIzTTJ0eWhWVk12VEpPbmdSdFNJCk9KbWdFNS9Ob0J0SWZlK2lmMGhn
            cWd5bTg5SUQzWnFnWlFlVWZGWTQzSmcKLS0tICtEL3ZGN25hTzNTTDF4ZFRmTlZB
            WjdSRWttL09HNEMzNlAxTzNQazRxVEEKqc9Ba8K0CwzH2IBYv9M9xwl+3cdh3r8I
            a4ufi9JhU9YPL6zYLhoXg5AEMAbCafTFhC0DO9P0+AoK7BnHXtbHdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T01:41:47Z"
    mac: ENC[AES256_GCM,data:B9MtZ6kKMuA/qwOJ5s6eIK8v7gtK653Qs1mAVl9rGu/IjcLX7Hh2FCWJdGZ+7P8xZIase0oWFOranhNJT5KW8xTiLpX5C+/C08pLBN9B2bmOecRu2rTv4T198Iwri0cBOyfN7phS/Mb2nL2+X/ENEqydrMs9Hg8Dpl/K6DsFtNU=,iv:N6gq95XYn/oQSEaBfgTMwNYNztdz6hc12VpwrsRhEus=,tag:XfUjvOVkbX3mZxAhfCbgpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
