apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hZIF/vbRT5lx,iv:UDCHlAj+hr2TrNlgRWrGQuozy6ty41FsVFYeCGjtiow=,tag:RZIzdSK+8QxQ4fiGy9r/GQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Kl+9PKqeinxZd+Nt6wHM2Q==,iv:6euwk1MO3qaDEXZRcEs4uHQ1Kw9qTfpmzifiuJ0YLMU=,tag:l9hTOTSOvZ1nCr00IoEX5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeTVjRTBmSTU3TmVraFl4
            dmZpWXY2VS9DUGRMdUxOSXRQNStjOXZ3QWswCmdmVi9LUFAxeFhRY3Bncm15WExV
            TnhORWxVZmNRRHhjOVhTUVNYellDVmMKLS0tIGQzNG5PdmpTOG5ocFNwVHV2bG81
            QkdpQnVPZDMwL0Y1ZUtORmc5c3dMU0kKw+P4KjC3N0PmGTJf1i2mG4ysDo6J/asi
            CL5niKFBJA2nLfnjfB1XWNAlZY/RCe/5KQHe3J6qmix09zUJqAx9jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T13:55:03Z"
    mac: ENC[AES256_GCM,data:UcQUfycSMz5ZWDbDQ5Goa0gSTZkkza76rUz3At47gmL3OKxRwBOUslqJcD92YYgbD7jbZnSHtvm8N/R9QjDkv5yDa1kDv63JgFLbFGROhUh0w8Y9Ggaxqn85M8v8vbAdXCm/htx6NdDEx7PEKdoZfK59eGLadgBYvVoaZsigKLs=,iv:xKW4iOTQt85KOQ/OzyIYeWJjJJBX4Vk2PAejMsyi85I=,tag:b1523s6rtesdF8zIJbAexw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
