apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1GlaXUJrxf2P,iv:yTqcwbBaI7gcq0LRUMsjVnDSdMYt1KpEexM/p3gy2JY=,tag:6FEQQQfBNoz8qVJACfYcPg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7j2bgkI65eWiqYNQvuO1DQ==,iv:AWi2R9tmcJQj1kyV7i6FrSBYGd1IX+0T05PRWGV/14Y=,tag:Mi0860+i8KwQAP95wDg7GA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xlohM88IZIzYtEE2jNnOGM/DkiIoWdpmnXSE7TbmaxGj3wUT,iv:KbQRCXWwXyd/pMJTGsn8Iui6xSMlqk5fgB+Ym3MM9+I=,tag:6AACDavaC+/mZOGpOB8NgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMUw0Q1U1dWNNT3dBMDh1
            ZlRiWGdMUXJEOTA1MWdsL25lKy9VUjRtL204CnNhOTVNQkhlaEJyUGRtTU5MUGE1
            eC9tdlFGZ0dnNHZENlpHNFJPd1pMMzgKLS0tIGorWlVwd3dEbVczTUNQcmdGeElM
            Y3hxSHdKSkphMTEvRDFHbXRncTBkNjAKCgDqpvZglfzEEfYBAEesTfxN/E/sK1Mm
            vLqwpe80/I+j32RR+TAbDbm4RDkfNCx/EfJtAMSGuD3mShklP3reZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T03:03:42Z"
    mac: ENC[AES256_GCM,data:70L/rHk8slVXi/mSDubKrccKwgOxQQxKIQDU7BNJZLFdDdww07MHpLp1VEPOT4pxUEs2arL4SEiDy6psGdlQU9o6LitpHM4B5hevvUlYnue1JbISJJam5wHIAQpGT/Vt7conrLNy5HyhITFFgQruIsmbDnpign6yUfrVjdDpsnQ=,iv:Krvl7MNIwrA4UAYMWfCGHpll5Nyovb4Q6vG9Mk0vCsE=,tag:wbMi4xA5X4feDGmRxtD/cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
