apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4vVOuUR/hq6T,iv:3rycHhEu0+Z9vAnPt+GRVSMpS0YArzDHBXnzHiyh6qM=,tag:5rUH9z/iCmMBrVUpnKE0cA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZSwu2pgWDEgWJvQWB46UQA==,iv:1IVlaBo98dWoWKLlk8ou3RaUq4xv8sMpBBzdnkql1Xw=,tag:qYB/n7+WWEVYmwCrinxLLg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2wikBAb6S47ArgyTjY6FkpsI9O63o83t8yK227zAYBLCKJyZ,iv:CO/cYwMmMVvckswRSXfn77rsL0BH//LJnE8e/iW+tos=,tag:tFya/jeJr4/ggf+HxgJmcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cmZPS3I5S0ZRMmNEWE1v
            TndHdWZLU3FEVENqdUFsbThBMkFad0xVL1VZCkk5QU9TTjZLQXNLamI1Tjl1cUpC
            WmZEdi9hOE9KVHhyUTFEY2VOb2Vud2cKLS0tIHhrdnBvSjFQMkNudXlSMmQyaTZh
            UkpSOXpPM085SFVCU1crbGExZXZKelUKjT1i52BytlaulKatxhXXPVSZJEBGfOuS
            Tq7DtuiK6cojoR/oREnVmnd1sfOGvqghADJ2fyx6JJSIoVeynMoZlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T03:03:09Z"
    mac: ENC[AES256_GCM,data:e0U0a+PxON8CvMz4a9or0/F3WkRaFjQ0XoKQnz/OoUJjayMJqzYSqkCkeDR+jCp0ZVwwC3IcuMAL+/BOf81DJM6Xnsb9+XrhEsT2bi7kUncLPQkS0d0SQ19n+mQkH+TRdqNF9Flb20G0TnxVvp8SxbsddOlkqA8RKIzY1OX+Jss=,iv:MpplM/q9ZQ0f3smzsKKTlQOZJzd9ukNGib3GZiSBsIo=,tag:zatU9fcohTba/9ymJCZD4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
