apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GbRARuRrrRel,iv:Mc2Ae36moh3rr1Cmc+kkvqP1kkDcQkOK54UaLG3lx1U=,tag:vWqRNbv+yLZX+GJcGkmq8A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GL4PnswDk+5fdRP3NgnfGw==,iv:OsvUpxqWyWEoXEzyoejOFu7QmWaZY1YnWigzO3eQZRQ=,tag:L4d5KwJt/i5DZ3XGWRji3g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gUyaJyu2xVDmew1KpOSXTFiY87/AC0ppyEnijdIaqCaHqCTZ,iv:LreEw6mGdN5m76EzS80Iag2vcNCJ+nIy2qyLklosiGo=,tag:Fd+NEKqsbGgeU+5mjUbnAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Wm5YRWd6OElLSlRuNlFO
            b1Z4Rm1TTGlFaVRvYllNRk01YnhqUE16a3hnCk00S3FWeDMwWlp4U1JiRlBsTmlP
            WVYwajNiWnRiYjd1SzJ5dTV0amFHWWMKLS0tIGpJaEJZakpFN3ByNGY2QzY2N25L
            UjgzTkp5MzNvVzZHWHR4UmRIbjZ2NEEKqfs1iQkqX2/uxdlc/EnRA1b3WHE6A9Wd
            pwlgsMQdBKoYiJyhvPF9afawafivMA2sObQmwOXizbDv2TJWaqmRAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T01:06:56Z"
    mac: ENC[AES256_GCM,data:L/+16+F0Ofz4+LUVsoFC3eAu0Qe4vxJ/QgDgdhGdgNyaCf0igtRR7Akaocot/iYi8ohAw+6SYOTF7b4CZKHZXMvvVwxUJjzq9UDBOcKOf2iUhtdbP9JTVcgYefV1nkLcCpawdPTWhtVx8zFAkfyEv2/Jh3ZUYVP0qDmp1o3vACQ=,iv:rIk9+cs3+3fGuflVEACpkk2NXPbsni5Zxv/cJQkn0iE=,tag:9EF62CKoCi6XFamHkfjxYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
