apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:QCcpBTrZ5HqIJpquU1c=,iv:Qx1o8gqZxJX/w+O6NG6bKSD/K5vl2EedQJ87P3Mupko=,tag:w8ttkUwsfSnbTz+gpMBuEw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MEdFeGEWWjWj9fZu26C/6A==,iv:69Tf1nDyhXQ868giLTzFZOUDQLT33b2W1l1jSRbVvvE=,tag:vVSq3b70maVMwkZOhpaXiw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VRaCFJGvDnGvKPQF+hB3t5sLKalvOWUXasQhw/uyBlcQQJbf,iv:DFeNL239fmH4nrhFRJLhEq6ubLsbga3IuEMV96vqpv0=,tag:zu/Vvoiaz/OHjMxnHOJQCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMVIwcHNHQjFlditucDR1
            bHZPSlJtd1lsRmhUM0xwY0NUNDBlWEhMWGpVCkQ4S1RHU0hrakxSZlJPckJSamxm
            RE5UaHhsV2FRY2hkcnFMNEFTb29VeXMKLS0tIHo0dTB5dWg3L0RhZ2tNZnhYV0Q5
            NGxiQjVtSEhROFhrd2UySk1sOFo5ajgKnQrUU4wzGHVpx0U8GzCo9Mtu2VO5nuxd
            3HkJEV7oYJ2IgFzbcR0IO8Uee6wRsRMrQSq+WILzer41RUqHbvMF/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T01:43:12Z"
    mac: ENC[AES256_GCM,data:Of0CR9DGKmZ0gfPbnMDCqhqk4r9rIOOCN1DdkcUD4kNhYcqqKeM18+vtntfoY1/h+OTqYih7D7BXDDnZgWbmcbCYqVMMHsWtIqzQzQA0Iy3S7JH4OeOO9tKlc2Arfetb4TNEeK2hK8RWLjQH4uUfzvnFBKEFuZJl9yRE+t4A3Pk=,iv:nsnADWpULK8wihkBpYy4Rfjs0EajVTRO5akA6d8xan8=,tag:dkS7L+5NhqqgXA92klnpIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
