---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: home-assistant-secret
        pod:
          # labels:
          #   ingress.home.arpa/nginx-external: allow
          #   egress.home.arpa/world: allow
          #   egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.100.30.11/24"]
              }]
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.1.4
            envFrom: *envFrom
            env:
              TZ: ${TIMEZONE}
              HOME_ASSISTANT_EXTERNAL_URL: https://hass.${SECRET_DOMAIN}
              HOME_ASSISTANT_TRUSTED_PROXIES: "${CLUSTER_CIDR}"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1
                memory: 2Gi
              limits:
                memory: 4Gi
            securityContext:
              privileged: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8123
    ingress:
      app:
        enabled: true
        className: internal
        # annotations:
        #   external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: home-assistant-config
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
      tmp:
        type: emptyDir
      # deploy-key:
      #   type: secret
      #   name: home-assistant-secret
      #   defaultMode: 256
      #   globalMounts:
      #     - path: /root/.ssh/id_rsa
      #       subPath: GH_DEPLOY_KEY
