apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:C3TSRdRnMIQG3jk+Xk/+UcVz/5xTYjccXBOamMdfKe4NJe9f,iv:qE3YZIgA0Zj2z9gyMBDQ3/YGC2qfDDuBTmkgLNE6mjA=,tag:abDLTr9o9Vo2qnVtlc3Egw==,type:str]
    credentials.json: ENC[AES256_GCM,data:guepf782wPhQV1aRy6l0g85XZxX51WNrAeL+lIzp9Q6rH7apO2+e98gNUUNSfb5hQpv4heaNZwdE6fjS/EgYW4RzdNWTtBFzg5X9ApCKGbtqtfgb6fcMYvXR0W921L8lhTsQ8a/KZ7MnP6zSP3E1x/ct7ZOLEt4fl6C/APLXKYR1QyfpkvHtywAi2Mqr9ZcSKIyr/JBjXGc5EWbUGVCsqNMX92n7sLiRiX57tXCINA==,iv:gHBluElfMNywIXyiiABf7xcpm22e9n7uY+kdzZMA0PU=,tag:DWtG85tXM8vdJGePYnmuPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTclEzTFcvWUxhY3RiQjc4
            MjZ1R0xZRlFkQWVPWUNTaGZJeTdReDZJZFRvCnRYelBDRCtodS9TbTZLVzBhbGRy
            MHRlZnprV2Ywd0N2RENtaXE3cS9MQkkKLS0tIGhPUkJJVzNQWFVhb3VUTlp6Sk5O
            WEhma1RoYzVxcEJodmtKdkgrbzUxalkKjU9MV+DK4veFDMy/fuFEJyuZDeEvfmFo
            lN5DiqKML2h7BaXdeQw33srNzkMLNPZ6O7dBn5Bm0kVpzZjn1DeYBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:49:01Z"
    mac: ENC[AES256_GCM,data:d9sYvo4XGhMSMw9lkiOJT2Yn5kyltQeWnqzhjw/6iQ84/Gxtc8z6y5LTzbcIUkIGFVLbyp1PvBN51XfmUM5CEof8qcvoIuqTg9IUd6L5CUutq5wm2d5L3qa8InCgqgCweRFa1hCTYhjJrwia5fCIbHDVkwAYtsmOfv5FTyRcvAQ=,iv:AWMLwt8zBhGOlP5h1q29zO4KpXWBPk8+EiMrViRB2Tw=,tag:hCutsfyRmjfdVd8LGAWe9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
