apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:D99QhfN8XwcIMpRef/Ecv3JNL21rtR9yrTaGygxR9az8nfaL,iv:tCC+49wgeHppjz8K4mD0JMoApGcxAnOq9bGsWggmSk4=,tag:IGrbHsmi6ZhgtyZhr7PWXw==,type:str]
    credentials.json: ENC[AES256_GCM,data:/t4bJ4KcZ+bBNuLh0SMaoX2DMFehY2VIvi7rZV/IYrSAF1ulr2ilvcDalW/GY+DuV418xWbqpZkk3QtwhSHw6PVHMhXFZrJdrqt3EBvIl8rUm6rZY/nyja4r98JLqp5B3NRi5XzujfbixwbVdUyBJUbglAgcT7ed777jagGBaBiuKIqheO1Bcp9E6qnr2giJffBMU+MckWk5YjZFLPcs8ABM2bmpRIsnd14znvc5rA==,iv:J2z+YVndJpW/ONIaumSi4RwioLFYMwJyaD0B1PCqJuo=,tag:Z1T1v8CaBx7TfWC3haVkLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY09DSFVqMFJaRWZIRUVU
            elE2MzdIUEYveVpid3dENGZmVFpKeE5mNjMwCnFHMUxpa1V5TjByT1VxSkRIVEJI
            elhRY3dWMnh6WndobUZLV0dyYmhkVnMKLS0tIDZUSitFbkpQMjJaV0hXOUF4RkFX
            c0o2R1FjbytlclV1Vno4b0hPQ04zNFUK+LNp2LcpPLXuxBpnsuXAUqm+FFa/IzGz
            SE3pbT7mE4vvJ++OgwdDgm2Txe2Cd4zp3rZbhQ4VjUHIUpOCu3/8UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-14T03:03:09Z"
    mac: ENC[AES256_GCM,data:hQjFIs8PxHJPsDYbLCWbPCz+K/biWfYYTL5Y1Wr4YqFGlLUf9AvMuS8yKGLnAiRxnRh6pIqYRU7/t2NIBEOoDdFsbPH/QNpomh1swaS/jE4eIxYfYaLhv2x16c7Uy0tIwJzA44AkhslgsNC3mdgATmd9knRlUwioS9vmkGUIqxY=,iv:DLktXHkuChcvuleBv4s5yrHIGB8K9Cth5HtaL2DccGA=,tag:T20aELil/ge9j40kQJPWvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
