apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:D2mMqQbaOrckbmWjeTsAtl+FpW3UDboZq5YXnFu0bT3JKCO9,iv:xrotCFaCSqv2lKWrW87SPE4TD5fzoY9KzeSR3k7gGu4=,tag:+VtfeyfY42L8lIDQ0dNfow==,type:str]
    credentials.json: ENC[AES256_GCM,data:m8Ynq4z+Lvp6J4MDam5isDPpMcJhECErhv9TGPD4jC1aGWuNa6gL8dGUxSnLzQIM2MeuDvMrYJCDWbJSC57laulnxqhgcQd2uitGN1RZN0tiI35XYmTsUnfrE6jTr+3yLdqr+LayTz4mrhURBufV+7eqZ02wS4ZbH+iNuHTFF/evrzs5reLMRFzLPKlD38O3/zZUPrwvFovkCDLlqN8GAe/Di1OJqAbgGUfj3odz0w==,iv:GtjZF3eG6jpLRY5X5O13tjCIkqmDkWoy/fkiQ++/uhc=,tag:Y2V+dOqP5f8w1Vtbzni3EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtwayu4z8c69uw69t9lsze5j6vf3grzyp97tlapg2d0xmdr3ccdsvsngn6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5L01uSFNZK0lKaXdRMkNR
            b0xHVWFUR1phVzdqVTRXUDRLSDN1NVJZempZCmh2UUlDaVYzQVhaakxlSzR6VnQ1
            NzFGRk9ab2ttZHJVcEZjRVZZdWhTSjAKLS0tIGJRUDZjLzBXTU01eDk1ZkRzV2lG
            Zm1xYTFwZHZnTjVYQ0RRN2RXNTBjZ2sKoxqQ9oHmGfPGGyE0z6mhCZEl4RbLHv6x
            y+NLG1qDP0bPI9698bxokxJ3fzNhsIEHk8XeRmkdht0X8+IQso1pgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-30T00:35:08Z"
    mac: ENC[AES256_GCM,data:w5pB4eHhmpRlDUafKkDLGZA6Ii1/whdcqbhNTOrhJIkJGloz2xamDDiDiW3iN8RfnYKR4FcahORRYTo8ErJeK35bxWGEx8NeXZpQcPbHfZF4YuZjHLLPyab4iXzpqn63dNz4uTZBeHQYfKZgJgr0cM21Zg094v4zWhqPCh+qt+4=,iv:IA/+AH9PPXmD7+9kflVgHJ/muKQq6ErM2hC9F01XBbE=,tag:AQxHP7BpROa1TJ5x23pa+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
