---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gitea-secret
    creationPolicy: Owner
    template:
      data:
        # App
        GITEA__database__HOST: "postgres-rw.db.svc.cluster.local:5432"
        GITEA__database__NAME: &dbName "gitea"
        GITEA__database__USER: &dbUser "gitea"
        GITEA__database__PASSWD: &dbPass "{{ .GITEA__database__PASSWD }}"
        GITEA__MAILER__SMTP_ADDR: "{{ .SMTP_HOST }}"
        GITEA__MAILER__SMTP_PORT: "{{ .SMTP_PORT }}"
        GITEA__MAILER__USER: "{{ .SMTP_USERNAME }}"
        GITEA__MAILER__PASSWD: "{{ .SMTP_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: "postgres-rw.db.svc.cluster.local"
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: gitea
    - extract:
        key: smtp
