---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea
spec:
  storageClassName: gitea
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.100.50.5"
    path: /tank/gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: development
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gitea
  resources:
    requests:
      storage: 1Mi
