apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:T+AbwMeu2kor7/RAIj3g91l0g/qZUw50MWdCdprB6H4=,iv:c3UPvrj8jeCIUT8Gx9YRRJM5ckxIxhg2e7VzmtEOYAw=,tag:8sEEEguLVosn5iKgQUDOYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bzgvTk02OUgvd0srZENW
            Wnc1NWpTaGxiMVFOdk9NWVBQSmI0VU5va1RJCitESTMzUld6ZXFrRFFEeGY1THY0
            ZW53MytyRmZWYk40dWd1Z3d6azJ6dXMKLS0tIGxQc0NmMVEzRExHdHZZaUsvTTN4
            SHRpWE9aWnJYb2NybXhkd3dkTjdZQTQK3SIYI1Ag7wMkURjnZ9jKnRiFiXhmhwht
            jHenbKNUDiIrYdgpujy3yeL3lH/oZlqvrQMSAizAY0rJXRnjCWdzXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T23:34:16Z"
    mac: ENC[AES256_GCM,data:PVaQSknuc5ySBDZzfQ8gTvYMsiMUm+hqd9qjWwJ/QaMI2m/wcPn3Pn79gUGYpEMxSqDJuqpAE3IWMHo8FUjBFU27ZPRWdwDFrC14644lqBNoj1btcdH2kkJSq7YlpdWzVkiWo4NhEJfXrg2AO21say+KCM/xL8Ap+b82yA/FlJM=,iv:w1fM4jo0iiJQOw7dVz2ObcbAj7WXQ8SyHWX/qMknh/0=,tag:SzWUlKI83Fvgvvx6qGBEbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
