apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WDWUDSVOTc4GVy0pykxglHPQVoa9+EBImXxkIYU0uv4=,iv:BvInbUWGkATzO1C6Bj2dZzvPuInOEQU5oYZC/H9Owg4=,tag:usS/UHvOb2brQmNl7j3yMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU1RsMTZ4V3NsQ0pETjZh
            ZisxblBUbFRIS2V3WXBkU1NkUjdCbVdlRVdzCmQzenNIUWtFYk00K2lHa1RuRUIx
            bll1YW9yRnA1bnliMVd1dnVySkc1WDQKLS0tIFFsVG96ZHRmcjIrM3RzNXlSWHBM
            WEROUzlCMUJ3Qkwzb2syOXlObGtrMmMKZyPLrk8edmC5E5DbyFGhUeSYCGwkcLLE
            JuEXYZgCi2H0o2z5GMnn8dGFGVf3o7Myz5eCOht3MaSnWqG/bJHdww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T21:57:21Z"
    mac: ENC[AES256_GCM,data:FhQIMXtnPT2eLywCHiSsPiJjr2nClCPt7aN1Sefah92iBAiv004NXwBbNK1+gjPf4OlylDmD8Z2pv/+1t0lTRRSoNBnbjOyNTNxRV2MpUw29KiGd7lQFRj2D1JdNf/WHmetpXUqPF5Bdwqn89UGJyuFVVd0zw+GV6aooPdpA2FI=,iv:pyYOMqfP2ykeUL2HiQPjnzhxoMvjK1Dpo/8KMVjXT7c=,tag:3ECXYTjx2y3V03DfBVUmwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
