---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authelia
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----
MIIJKwIBAAKCAgEA0tab2K6ggNZ+ia5QZPIgjDzKnhPi12LlflIWCtpVEnxVWP8I
ku+tGEufN5DUuxyvZxY/nHuR0tHQC9cHqill8H8Zuhbhe8Jy9FDIISLhXBogZXgZ
mY0zSen9vfP1tegTbI+TMI+++9txcATvS/EnwCrtg3ejrmtd9dYhV32n1340Kiud
/JDcefsrPsU2NzG1AG96ywafap/Hy49rOa4SAU7CxqStWrQh0VmVCti6v/BAeM6r
m/BL2P5zCtAuCusw655hIYpvn0uyp1SnH+k31IR5DujY4xWdPpBURY/E0CilIwbz
VybiPZfDXtD0nCKv4h2+L/xQJdguGBdkw/f03LD2mdpPqeq7+pEkagjFfmb0DT2V
Ha2/9zgmEcdJ7YRYDj/+FKrs7yNHej3FuNk/f5h9mmlwWqEcT9wNTPSVFx8jO4KR
a8BmqV2Irgpoc4Cjf8+nyFj9HbkW4jtJxPYXUtqj+7X+67yuXzSCo9j1S1oDmpwd
uZkeb2JOOxl6Dk8sRiN4KruYeV4aJ7KmTXCJ0IWzrtr85CrdCFIyZok4Lijq3C2y
UMNa7AbvX5MOLT+SdvrbgJFJxhSrJiigfTpqdIvpO9AfwkqIMY3TB9jIFR9+6R4b
2ogQ/eCOdoJZF7Hxa1zNvBJaogbri8Z0rP6gZn6t0aIjm/HHVnIkb/a8GnECAwEA
AQKCAgEAo/zkTs7UbCFpXnFEep+RDUKjXfydrWVwlqYGGv7iuHQYdhY3dwIQohr/
hdqSe8695vJ5G59JNq6WoP7pKUL11O8m9YSicP43JyxF3PAiVN7FX+bgEnyu7cif
4cUE0i3mHcQ2ecj0hTSTsMtFzM2PW3qILn85wookFPguCrzjdUrmC/7M7QtHUWE4
q6P8nUV+QQ50dcF68RXB8uRkRALOYlH+UT74ztnYi9qfgEY+Stf1bYFiHPH0LJ0M
odZ2WWvBKyKO7eWdGEtqc5f2PW3KTPOUrTISr9255lWgFlLShA15FBtt3dWSltGZ
1f+0olSgdMEpkm0vcaAJihd3+qy7uBo6+bEuvAa4w1WBkgcusEA1RVPDhUbUlFJw
neB7QFAwq6gGRHBbbqzJLGjJgtS85M2aLqYYq+rCygYWzokbyDX3kcJ0Mqv0ress
487aP3xPlxTAqvyADN2IEmiqng7UWiRv417CuFDUP1m4JQMURoC1x2thI0cJgGOd
VZB/hSnVTJbiePKQL4FOo0QaUju/cGpf1TWfTa8DoiVsPrULV4DesSfsbIbxuYLS
prNCWbFid3Vd2KEVWwV/dBlTA5LNnZNw5KhF+ENbof5iZyZ2WV3HVwHE7r98Ooyg
56xUUB7Jqggz/iv8feY+eFD7AdNMpK0mV0pNAhDRPiSYuBqS+TkCggEBAOztbUvH
pw/exmeNSceEBem6ivET7hjGYhZxFcYDtVrEDSxYagUIZgHEBCpmdv4Ymyp31gMp
Y4CaimeFIOk2xwy4aUbmlNa3fLts8DAUCsIqgM6r4e9ga4gfMYwvRnSaVB28eZEi
UvmxD2LZyylLHFy34aX/81pEBex6WqGDKO4WbXWSbS2NDH8Y6vdjPeuxLYIFQZY5
v5ZtVODPAONeFqxaenHFdYznAWiQ0tvPzL7lz2vnZRM1UrAhqD2xzKsTkWmCaSaB
eTsXjdRdIklDxjeFp43SJa5SHOZiSZEdXnrtt/DtCJYIXmbcqrS6E+4LTJ9+DY3U
YAGMhJgAhbtP8HcCggEBAOPPij/hypluahlk8mOA2m/gzLtzOqOUgrmu4DeCDz6d
t8UKYPrO5R2oQfdCJpMLhhdDv+DPvS8eLYKW/o3VK7uYWoO3MDnuhky8zC/6PUyq
N2askjmgBh+059qUjJ7yPNuwqD+616Q4itb0mN5N4NHIRYk+MbgTCOYBEgc4qwPN
H4+twRCvhO4KXVoOEKS/qm2T2gLmJA5RV1S/+Z1S89aR/7AvfPhJgcsORxlU1NE/
0eVonJZykM7snxcaDn7XM6T8V6ddfymYkay46jTwhEf2vbdSDPo78NAW65PfCsoa
1C/K2lEwCJxuJZrB02aW+CySteIqq8C5OQ74G6yELlcCggEBAMVc7tvef9Mfj4T5
VEloOAjAhTdXk9J9h34MS8f8lNj8UcDsEb0JhvfXkmTDoEIAu1kAJH3Tv3iEw+CC
LK05HU0CXWhbcgb/KF902wwh1ehywYPn+LiQSGNHIN4XD4jYelOfCmGVByvKi/eb
V7qZQBIYd1bxxIUf/xNDxTWf7buPYTU8ecglJBDH8AuOVyl8GV2jBUSf7HHht3/h
0GqWmSqP4Enf5BEw6aJyacQD8RnglA3d3vvGQpBIKT7jWov0LACJSxBxcEyCTXpm
7sW7OGZN5wqj0RHKgxqDK6c/oNGkLsL6oVlhtUnYbjdIfougS/7cYWwRSrxfkqCQ
ZtZnO/cCggEBALSTEdbJNzqfVuKCLc/Jl1wPKLl9AQIg+e4NPBVDtqm/gqdhLrYf
wWTctk0z1jfAbq2KOlIM2Ly8gv58iZILYvr0LOszDbsd4r54+LEe/fADDJ8KM24R
9kizsQSFs2FaSfsp8HNzuvKlDwiMIZA00vv2b4f2EJsEG42VU6D9vjDpKxdMdziu
qAO3m3+Cnpa4hnMNO0YI/pOKzlqTQVz/H+D5IV+ahMiaG5PE4X6my3qBx/K8FUL7
1OTwkrpRISRRmNIyY5h6eA2UrgPnH16PN4uDfaYOF9NSJ/QJ9vnjVj4VPhQUCzFH
jcvRU2V0NgmfqWBLeninsjS1nRDMgcMhk0kCggEBAImbgi9L2rNh/hIi9ejSvHXE
n/39GWOFEbwPNMoXq956FKJ6/F3jp1t1Kokbv/r5lLcD07pOnYSTq9HxVe8mPaR4
72jrkISzqZF0wBdu54plHH5isIrjrick1uvfkgqYr3VJOTM41M/3pdRmcuPY7cYb
cc7u2faH8ldrjwPMQPL9QkAFX8iPczq2nMU7K5KqoS4T5viYJ4jFuUtXVuKuh6aO
w/BUbrTS4NR4APM7Wc0jzBCU8lqF7nrEVj6RcLgMlO8ihqvbFj0AIDvRTApXkFFr
2BSRzBIDBwsM9AWqiH7aQkaqk5SvZpwNeH9TUrW+RLuyCqtCcsaF6I3enMCc/hI=
-----END RSA PRIVATE KEY-----"
        AUTHELIA_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbname authelia
        AUTHELIA_STORAGE_POSTGRES_HOST: &dbhost postgres-rw.default.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: "{{ .AUTHELIA_POSTGRES_PASSWORD }}"
        AUTHELIA_STORAGE_POSTGRES_USERNAME: "{{ .AUTHELIA_POSTGRES_USERNAME }}"
        # OIDC Apps
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        # IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT_SECRET }}"
        # MINIFLUX_OAUTH_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}"
        # WEAVEGITOPS_OAUTH_CLIENT_SECRET: "{{ .WEAVEGITOPS_OAUTH_CLIENT_SECRET }}"
        # GITEA_OAUTH_CLIENT_SECRET: "{{ .GITEA_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        POSTGRES_DB: *dbname
        POSTGRES_HOST: *dbhost
        POSTGRES_PASS: "{{ .AUTHELIA_POSTGRES_PASSWORD }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_USER: "{{ .AUTHELIA_POSTGRES_USERNAME }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: cloudnative-pg
