---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name readarr
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
