---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellystat
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init:sha256-a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
            envFrom: &envFrom
              - secretRef:
                  name: jellystat-secret
        containers:
          main:
            image:
              repository: docker.io/cyfershepard/jellystat
              tag: 1.1.3
            env:
              TZ: "America/Chicago"
            envFrom:
              - secretRef:
                  name: jellystat-secret
    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 3000
    ingress:
      main:
        className: internal
        hosts:
          - host: &host "jellystat.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: *httpPort
        tls:
          - hosts:
              - *host
    # persistence:
    #   backup:
    #     type: emptyDir
    #     advancedMounts:
    #       main:
    #         main:
    #           - path: /app/backend/backup-data
