apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:7XDaoMI39X4zKmNiUk1JOIm+aMVxXmmSKFzsaLIZ/x8KVc2rywGkeQ==,iv:UDsvP7Ny5sxBxkApizKdDl1uqqewNbkrN8buX8v6XqM=,tag:oFlROKlCRG1niGtlq8tOEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMTlYZXN3ZnhVWDgyTENt
            RnNoR21ObXFGM1M0RTJKTnFIYitkN2wwQzFFCmticFNyZlhVSElhZ2NrUTA4UVV3
            T2R0NDc5Z3RPM0Uxc3lSZEI0eHZRTUkKLS0tIGtHQUlkelhsYXhlQzRUWWExVUli
            VlR2Z3FxdWVUUzNxSFA1QkVibVozdncKolFQ+d2M1eaLurawNPZzgBLE/kr4TOnL
            XVZ2zVIeFNPOhnP2VZN1uk6MOx5HU7PEuFLg0Xfk39inepgfFQgVmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T19:29:36Z"
    mac: ENC[AES256_GCM,data:iDx1YJhKC41xYY9OsSu5HoJRhWAuewaUJ1eeetITMANej6hCBC8+hcERXjF+TSYj3AUlgV5HpRL15I+n+D5xKatOiUR4I8sSDeKGtpoxef0P5K8X1Ii6TYG6uaezmjkbKsJX6IDPvZ68HtTKXuh76gHUr2ZxhEZh0GYwuTS1OUs=,iv:2adX6yzyuj9LfP5E3PMzLWeJ3o0WfGJzNpgpbj1GYUw=,tag:U3Cl4qcE0aV5cYOnIo7/gw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
