apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:IiYM1bQ0M33oiNTbFPzHDZeQHV7+lnrd7sOVvXLMETLctcqQau1WKw==,iv:mGxjlhdYzk1gCFB3zS6UPgs8qzttAxI1Atp6aLUtPxk=,tag:snBJulqDoZYDyhgiF9BiIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZjl1cmM5Z1JPK2UxMFhI
            TDEvdXU2K2t2RWNPaE1GKzBPS3JYS2ovM3g4CnZoRlhhOG1hSkZHMHIrMXNGL3p0
            d3d3bi9JUUlRamhjK29ITDVGaU8zVlEKLS0tIGtueHZyUkRVckU1cEpqL0Y4R2dJ
            VGN1MVlaY1N1MWFvY0FBMGMwaVBzMGcKmji/GV9lv7G0dSswhzksMlNGPZUUUX/T
            wyiMrE93tgXak3SmHEaf5sXQ1DGBIx8wvVnkELib4TOPolnyl0I4vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T03:14:17Z"
    mac: ENC[AES256_GCM,data:2ZYkGk1W6IrXfJ7V31lTQZPAiCPl68yfv0HeTMPhyZYuyFRd5phVzQ5cmUASKI6T7epByOEHm8es+lXZVDwygfD/0DutSMFvE7jtjYRUJ0oxMvDioX+vjCWZE5A5Nl91Db3fZBpoCxdMJ7vLNVykv0dcdMTBWfLsQL4kImf6W98=,iv:fW1TPo29VS7Vv3kqaYeWaGTr8HBIi3G7S5u/oFXWCQE=,tag:bpkndrK58HZyDGASC5iUCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
