apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9EiBH/J6k7GIXIBfPRJAHUK3rYtVkAzYg0XNqwLbQVRlakmFfuKXGQ==,iv:I5AGyqVk4kpb06SCQ4TOpXs+HcKJT0yO5l9dJr1/9JU=,tag:66WJY2GH3gN1o+V7Leyu0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tfeqmhtjnz5tz9jst8nlzmchmpndt67r7fz7tq244q0p2ufqygqdp65ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMXY5ZmlNaHVyYllldFBJ
            cnBDYTFJRXNHbmYrVldiZlFrM0UwYVBpeHhBCkxRd1pEOFZkVi95TnpmL1dteER1
            c3R2OEFJQ2kyNDUrZnpCLzZsT3cwZjgKLS0tIEF0QURrUFZ5ZjBYbzlPQXFoUE1Y
            ZmFhZjJPRkt3bDIyVEdUTWtDYXZuUUkKhVQBwqARfi4ZIxek9sRSfLtrWU2K83eh
            wXsLxs8IaGhEs3l2OzOicROCJeBBeSGhApCwvrBKJTv14EOOrmMzGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T01:41:47Z"
    mac: ENC[AES256_GCM,data:Lti/p0548BgAxOgQa9nrf5udYrM1o1wKYS0/sTTulIzuH1Vj3UAvseqmP5i3MRW7EcaFZiBHwyGU3v5xbOCVhgDTfGibH3KiUoeq33cdg0ouG9PCvo7/oNswiDndK/RdrAYb2JbSoCpBbgyv5tyHgkBTf/83oFm2dO/qI+oUvBk=,iv:vSsKt1Ec6myHbj8kXPF+YFPtbSa4T6ugptf9rXYFnu8=,tag:c0oX6jLEg7WDyCU3pYbaMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
