---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin
  namespace: db
  labels:
    app.kubernetes.io/name: &name pgadmin
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
