---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefly
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: home-automation
  dependsOn:
    - name: external-secrets-stores
    - name: rook-ceph-cluster
    - name: redis
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/home-automation/firefly/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
