---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefly
  namespace: flux-system
spec:
  targetNamespace: home-automation
  dependsOn:
    - name: external-secrets-stores
    - name: rook-ceph-cluster
    - name: redis
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/home-automation/firefly/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
