---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: firefly-secret
    creationPolicy: Owner
    template:
      data:
        # App
        SITE_OWNER: phekno@gmail.com
        APP_KEY: "{{ .APP_KEY }}"
        DB_CONNECTION: pgsql
        DB_HOST: &dbHost postgres-rw.db.svc.cluster.local
        DB_PORT: "5432"
        DB_PASSWORD: &dbPass "${{ .DB_PASSWORD }}"
        MAIL_MAILER: smtp
        MAIL_HOST: "${{ .SMTP_HOST }}"
        MAIL_PORT: "${{ .SMTP_PORT }}"
        MAIL_FROM: firefly@phekno.io
        MAIL_USERNAME: "${{ .SMTP_USERNAME }}"
        MAIL_PASSWORD: "${{ .SMTP_PASSWORD }}"
        MAIL_ENCRYPTION: tls
        MAP_DEFAULT_LAT: "45.108885995445156"
        MAP_DEFAULT_LONG: "-93.42319876926108"
        STATIC_CRON_TOKEN: "${{ .STATIC_CRON_TOKEN }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: firefly
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: firefly
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: firefly
    - extract:
        key: smtp
